package main

import (
	_ "embed"
	"encoding/json"
	"log"
)

// examplesJSON is generated by cmd/gsx-examples from the single-source
// examples/*.txtar fixtures (see internal/examplegen). It is the same preset
// list the docs page and the frontend dropdown use, so the cache-seed can never
// drift from the documented examples.
//
//go:embed examples.json
var examplesJSON []byte

// presets are the default examples, seeded into the response cache at startup so
// visitors get instant first renders. Built from the embedded examples.json.
var presets = mustLoadPresets()

func mustLoadPresets() []renderReq {
	var raw []struct {
		Source string `json:"source"`
		Invoke string `json:"invoke"`
	}
	if err := json.Unmarshal(examplesJSON, &raw); err != nil {
		log.Fatalf("presets: parse embedded examples.json: %v", err)
	}
	out := make([]renderReq, len(raw))
	for i, r := range raw {
		out[i] = renderReq{GSX: r.Source, Invoke: r.Invoke}
	}
	return out
}

// seedPresets renders each preset once so it is warm in the response cache.
// Intended to run in a background goroutine after the server starts listening.
func (p *pool) seedPresets() {
	for _, pr := range presets {
		p.render(pr)
	}
}
