version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - durationcheck
    - govet
    - ineffassign
    - misspell
    - modernize
    - staticcheck
    - unused

  exclusions:
    generated: strict
    paths:
      - '.*\.x\.go$'

  settings:
    staticcheck:
      checks:
        - SA*
        - QF*

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  show-stats: false
