// Code generated by internal/htmldata/gen. DO NOT EDIT.

package gsx

// trueFalseAttr reports whether HTML's own value vocabulary for this
// attribute is the literal strings "true" and "false" — every attribute in
// the @vscode/web-custom-data dataset whose valueSet lists both. That is the
// aria-* state set plus draggable and spellcheck. The argument must already
// be lowercased.
//
// These are the ONLY names on which a bool stringifies; see BoolRendersBare.
// Dataset gaps are curated in trueFalseExtras.
func trueFalseAttr(name string) bool {
	switch name {
	case "aria-atomic",
		"aria-busy",
		"aria-checked",
		"aria-current",
		"aria-disabled",
		"aria-expanded",
		"aria-grabbed",
		"aria-haspopup",
		"aria-hidden",
		"aria-invalid",
		"aria-modal",
		"aria-multiline",
		"aria-multiselectable",
		"aria-pressed",
		"aria-readonly",
		"aria-required",
		"aria-selected",
		"draggable",
		"spellcheck",
		"virtualkeyboardpolicy":
		return true
	}
	return false
}
