package codegen

import (
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

var update = flag.Bool("update", false, "update golden files")

// TestGenerateSource checks the generated .x.go source (the lowering shape)
// against a golden file. It writes the fixture to a temp module, runs
// GeneratePackage, and goldens the generated bytes. Run with -update to
// regenerate.
func TestGenerateSource(t *testing.T) {
	repoRoot, _ := filepath.Abs("../..")
	tmp := t.TempDir()
	writeFile(t, tmp, "go.mod", "module gsxg\n\ngo 1.26.1\n\nrequire github.com/gsxhq/gsx v0.0.0\n\nreplace github.com/gsxhq/gsx => "+repoRoot+"\n")
	pkgDir := filepath.Join(tmp, "genpkg")
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, pkgDir, "views.gsx", `package views

component Greeting(name string, count int) {
	<p>Hello, {name}! You have {count} messages.</p>
}
`)
	gen, err := GeneratePackage(pkgDir)
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	var got string
	for _, src := range gen {
		got = string(src)
	}
	const golden = "testdata/greeting.x.go.golden"
	if *update {
		os.MkdirAll(filepath.Dir(golden), 0o755)
		if err := os.WriteFile(golden, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(golden)
	if err != nil {
		t.Fatalf("read golden (run -update): %v", err)
	}
	if got != string(want) {
		t.Fatalf("source mismatch (run -update):\n--- got ---\n%s", got)
	}
}

// TestRenderEndToEnd compiles and runs the generated code against the real
// runtime and asserts the rendered HTML — the seed of render.golden.
func TestRenderEndToEnd(t *testing.T) {
	files := map[string]string{
		"views.gsx": `package views

component Greeting(name string, count int) {
	<p>Hello, {name}! You have {count} messages.</p>
}
`,
	}
	got := renderPackage(t, files, `p.Greeting(p.GreetingProps{Name: "World", Count: 3})`)
	assertHTMLEqual(t, got, "<p>Hello, World! You have 3 messages.</p>")
}

func TestLineDirectives(t *testing.T) {
	repoRoot, _ := filepath.Abs("../..")
	tmp := t.TempDir()
	writeFile(t, tmp, "go.mod", "module gsxl\n\ngo 1.26.1\n\nrequire github.com/gsxhq/gsx v0.0.0\n\nreplace github.com/gsxhq/gsx => "+repoRoot+"\n")
	pkgDir := filepath.Join(tmp, "genpkg")
	os.MkdirAll(pkgDir, 0o755)
	writeFile(t, pkgDir, "views.gsx", "package views\n\ncomponent Greeting(name string) {\n\t<p>{name}</p>\n}\n")
	gen, err := GeneratePackage(pkgDir)
	if err != nil {
		t.Fatal(err)
	}
	var got string
	for _, src := range gen {
		got = string(src)
	}
	if !strings.Contains(got, "//line views.gsx:") {
		t.Fatalf("expected //line directives in generated source:\n%s", got)
	}
}

func writeFile(t *testing.T, dir, name, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}
