// Package codegen lowers a parsed gsx AST to Go source (.x.go) targeting the
// gsx runtime.
//
// SPIKE SCOPE (deliberately minimal — see docs plan): one or more components
// with inline params, static markup, and BARE-PARAMETER interpolation whose type
// is read syntactically from the param list (string -> gw.Text, int -> formatted
// -> gw.Text). Anything beyond a bare param (field access, calls, package funcs),
// attributes, control flow, methods, `?`, child components, etc. returns a clear
// "not yet" error — that boundary is exactly what this spike exists to surface
// (it is where go/types must eventually enter).
package codegen

import (
	"bytes"
	"fmt"
	goast "go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"sort"
	"strconv"
	"strings"

	"github.com/gsxhq/gsx/ast"
)

// Generate produces formatted .x.go source for a parsed gsx file.
func Generate(file *ast.File) ([]byte, error) {
	imports := map[string]bool{
		"context":              true,
		"io":                   true,
		"github.com/gsxhq/gsx": true,
	}
	var body bytes.Buffer
	for _, d := range file.Decls {
		comp, ok := d.(*ast.Component)
		if !ok {
			// SPIKE: pass-through Go (imports, helpers) not handled yet.
			continue
		}
		if err := genComponent(&body, comp, imports); err != nil {
			return nil, err
		}
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by gsx; DO NOT EDIT.\n\npackage %s\n\n", file.Package)
	writeImports(&b, imports)
	b.Write(body.Bytes())
	return format.Source(b.Bytes())
}

func writeImports(b *bytes.Buffer, imports map[string]bool) {
	var std, ext []string
	for imp := range imports {
		if strings.Contains(imp, ".") {
			ext = append(ext, imp)
		} else {
			std = append(std, imp)
		}
	}
	sort.Strings(std)
	sort.Strings(ext)
	b.WriteString("import (\n")
	for _, imp := range std {
		fmt.Fprintf(b, "\t%q\n", imp)
	}
	if len(std) > 0 && len(ext) > 0 {
		b.WriteString("\n")
	}
	for _, imp := range ext {
		fmt.Fprintf(b, "\t%q\n", imp)
	}
	b.WriteString(")\n\n")
}

func genComponent(b *bytes.Buffer, c *ast.Component, imports map[string]bool) error {
	if c.Recv != "" {
		return fmt.Errorf("codegen spike: method components not supported yet (%s)", c.Name)
	}
	params, err := parseParams(c.Params)
	if err != nil {
		return err
	}

	// Props struct.
	fmt.Fprintf(b, "type %sProps struct {\n", c.Name)
	for _, p := range params {
		fmt.Fprintf(b, "\t%s %s\n", fieldName(p.name), p.typ)
	}
	fmt.Fprintf(b, "}\n\n")

	// Render func.
	fmt.Fprintf(b, "func %s(p %sProps) gsx.Node {\n", c.Name, c.Name)
	b.WriteString("\treturn gsx.Func(func(ctx context.Context, w io.Writer) error {\n")
	b.WriteString("\t\tgw := gsx.W(w)\n")
	pm := paramTypes(params)
	for _, m := range c.Body {
		if err := genNode(b, m, pm, imports); err != nil {
			return err
		}
	}
	b.WriteString("\t\treturn gw.Err()\n")
	b.WriteString("\t})\n}\n\n")
	return nil
}

func genNode(b *bytes.Buffer, n ast.Markup, pm map[string]string, imports map[string]bool) error {
	switch t := n.(type) {
	case *ast.Text:
		emitS(b, t.Value)
	case *ast.Element:
		if len(t.Attrs) > 0 {
			return fmt.Errorf("codegen spike: element attributes not supported yet (<%s>)", t.Tag)
		}
		if t.Void {
			emitS(b, "<"+t.Tag+"/>")
			return nil
		}
		emitS(b, "<"+t.Tag+">")
		for _, c := range t.Children {
			if err := genNode(b, c, pm, imports); err != nil {
				return err
			}
		}
		emitS(b, "</"+t.Tag+">")
	case *ast.Interp:
		return genInterp(b, t, pm, imports)
	default:
		return fmt.Errorf("codegen spike: unsupported markup node %T", n)
	}
	return nil
}

// genInterp resolves an interpolation's type and emits the matching writer call.
// SPIKE: only a bare component parameter is resolvable (type from the param
// list). Anything else is the go/types boundary.
func genInterp(b *bytes.Buffer, n *ast.Interp, pm map[string]string, imports map[string]bool) error {
	if n.Try {
		return fmt.Errorf("codegen spike: `?` try-marker not supported yet")
	}
	expr := strings.TrimSpace(n.Expr)
	typ, ok := pm[expr]
	if !ok {
		return fmt.Errorf("codegen spike: interpolation %q is not a bare component parameter; "+
			"resolving its type needs go/types (not yet implemented) — this is the boundary the spike surfaces", expr)
	}
	field := "p." + fieldName(expr)
	switch typ {
	case "string":
		fmt.Fprintf(b, "\t\tgw.Text(%s)\n", field)
	case "int":
		imports["strconv"] = true
		fmt.Fprintf(b, "\t\tgw.Text(strconv.Itoa(%s))\n", field)
	default:
		return fmt.Errorf("codegen spike: interpolation of type %q not supported yet (only string, int)", typ)
	}
	return nil
}

func emitS(b *bytes.Buffer, s string) {
	fmt.Fprintf(b, "\t\tgw.S(%s)\n", strconv.Quote(s))
}

type param struct{ name, typ string }

// parseParams parses an inline param list ("name string, count int") into
// (name, Go-type) pairs by reusing go/parser on a synthesized function.
func parseParams(src string) ([]param, error) {
	src = strings.TrimSpace(src)
	if src == "" {
		return nil, nil
	}
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "", "package p\nfunc _("+src+") {}", 0)
	if err != nil {
		return nil, fmt.Errorf("codegen: parse params %q: %w", src, err)
	}
	fn := f.Decls[0].(*goast.FuncDecl)
	var out []param
	for _, field := range fn.Type.Params.List {
		var tb strings.Builder
		if err := printer.Fprint(&tb, fset, field.Type); err != nil {
			return nil, err
		}
		typ := tb.String()
		for _, nm := range field.Names {
			out = append(out, param{name: nm.Name, typ: typ})
		}
	}
	return out, nil
}

func paramTypes(params []param) map[string]string {
	m := make(map[string]string, len(params))
	for _, p := range params {
		m[p.name] = p.typ
	}
	return m
}

// fieldName maps a param name to its props struct field (first letter upper).
func fieldName(p string) string {
	if p == "" {
		return p
	}
	return strings.ToUpper(p[:1]) + p[1:]
}
