package codegen

import (
	"bytes"
	"errors"
	"fmt"
	goast "go/ast"
	"go/format"
	goparser "go/parser"
	"go/token"
	"go/types"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/gsxhq/gsx/ast"
	"github.com/gsxhq/gsx/internal/attrclass"
	"github.com/gsxhq/gsx/internal/cssmin"
	"github.com/gsxhq/gsx/internal/diag"
	"github.com/gsxhq/gsx/internal/jsmin"
)

// generateFile emits the .x.go for a parsed gsx file given already-resolved
// interpolation types. It returns (nil, false) if any component failed; all
// component errors are recorded in bag (component-boundary recovery continues
// to the next component on failure, so multiple errors are always reported).
func generateFile(file *ast.File, resolved map[ast.Node]types.Type, table filterTable, structFields, nodeProps map[string]map[string]bool, fset *token.FileSet, cls *attrclass.Classifier, bag *diag.Bag, cssMin, jsMin func(string) (string, error)) ([]byte, bool) {
	if cls == nil {
		cls = attrclass.Builtin()
	}
	interpTemp = 0
	// Minify the static CSS of <style> blocks. cssMin is nil for the built-in
	// safe minifier, or a custom override (e.g. tdewolff) threaded from
	// gen.WithCSSMinifier. Custom minifiers only ever receive complete, valid CSS
	// (holeless blocks); holey blocks always use the built-in hole-aware pass
	// regardless of cssMin.
	if err := cssmin.MinifyFile(file, cssMin); err != nil {
		bag.Add(diag.Diagnostic{Severity: diag.Error, Message: err.Error(), Source: "codegen"})
		return nil, false
	}
	// Minify the static JS of <script> blocks. jsMin is nil for the built-in
	// safe minifier (ASI-safe, newline-keeping), or a custom override threaded
	// from gen.WithJSMinifier. Only holeless <script> blocks are minified; a
	// script carrying any @{ } hole is left un-minified for safety (see jsmin).
	if err := jsmin.MinifyFile(file, jsMin); err != nil {
		bag.Add(diag.Diagnostic{Severity: diag.Error, Message: err.Error(), Source: "codegen"})
		return nil, false
	}
	imports := map[string]bool{
		"context":              true,
		"io":                   true,
		"github.com/gsxhq/gsx": true,
	}
	// Each GoChunk is split: its imports are folded into the import region (they
	// must precede all other declarations) and its non-import remainder flows
	// into the body. A single chunk may carry both — e.g. an import followed by
	// type/func decls. Aliased / dot / blank imports are kept verbatim; plain
	// imports merge into the import set so they dedupe against the runtime imports
	// the generator already needs.
	var aliased []importSpec
	var body bytes.Buffer
	ok := true
	for _, d := range file.Decls {
		switch v := d.(type) {
		case *ast.GoChunk:
			specs, rest, err := splitChunk(v.Src)
			if err != nil {
				bag.Errorf(v.Pos(), v.End(), "invalid-syntax", "%s", strings.TrimPrefix(err.Error(), "codegen: "))
				return nil, false
			}
			for _, s := range specs {
				if s.name == "" {
					imports[s.path] = true
				} else {
					aliased = append(aliased, s)
				}
			}
			if rest != "" {
				body.WriteString(rest)
				body.WriteString("\n\n")
			}
		case *ast.Component:
			// Recovery boundary: each component emits into its OWN temp buffer.
			// On failure, the diagnostic is already in bag — skip this component's
			// output and continue to the next (report ALL components' errors).
			var cbuf bytes.Buffer
			if genComponent(&cbuf, v, resolved, table, structFields, nodeProps, imports, fset, cls, bag) {
				body.Write(cbuf.Bytes())
			} else {
				ok = false
			}
		}
	}

	if !ok {
		return nil, false
	}

	// Build the path→reserved-alias map for the FILTER packages, harvested from
	// the table (every entry records its owning package's alias + path). A path in
	// `imports` that is a filter package is emitted under its reserved alias; std
	// keeps _gsxstd so std-only output is byte-identical to before.
	filterAlias := map[string]string{}
	for _, e := range table {
		filterAlias[e.pkgPath] = e.alias
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by gsx; DO NOT EDIT.\n\npackage %s\n\n", file.Package)
	writeImports(&b, imports, aliased, filterAlias)
	b.Write(body.Bytes())
	src, err := format.Source(b.Bytes())
	if err != nil {
		bag.Add(diag.Diagnostic{Severity: diag.Error, Message: fmt.Sprintf("format generated source: %s", err), Source: "codegen"})
		return nil, false
	}
	return src, true
}

// writeImports emits the generated file's import region. imports is the set of
// plain import paths the generator needs; aliased carries verbatim user GoChunk
// imports; filterAlias (path→reserved alias) names any FILTER package among
// `imports` so its import line uses the reserved alias the lowered calls
// reference (e.g. `_gsxstd "<std>"`, `_gsxf0 "<user>"`). Filter imports sort by
// alias and are emitted after the plain external imports, before user-aliased
// ones — std-only output keeps its single `_gsxstd "<std>"` line, byte-identical
// to before.
func writeImports(b *bytes.Buffer, imports map[string]bool, aliased []importSpec, filterAlias map[string]string) {
	var std, ext []string
	type filterImp struct{ alias, path string }
	var filters []filterImp
	for imp := range imports {
		switch {
		case filterAlias[imp] != "":
			// A filter package: the lowered calls reference <alias>.<Func>; the import
			// MUST use exactly that reserved alias (collision-safe — no user symbol can
			// start with _gsx). Emit it separately, not in the plain ext loop.
			filters = append(filters, filterImp{alias: filterAlias[imp], path: imp})
		case strings.Contains(imp, "."):
			ext = append(ext, imp)
		default:
			std = append(std, imp)
		}
	}
	sort.Strings(std)
	sort.Strings(ext)
	sort.Slice(filters, func(i, j int) bool { return filters[i].alias < filters[j].alias })
	sort.Slice(aliased, func(i, j int) bool { return aliased[i].path < aliased[j].path })
	b.WriteString("import (\n")
	for _, imp := range std {
		fmt.Fprintf(b, "\t%q\n", imp)
	}
	if len(std) > 0 && (len(ext) > 0 || len(aliased) > 0 || len(filters) > 0) {
		b.WriteString("\n")
	}
	for _, imp := range ext {
		fmt.Fprintf(b, "\t%q\n", imp)
	}
	for _, f := range filters {
		fmt.Fprintf(b, "\t%s %q\n", f.alias, f.path)
	}
	for _, imp := range aliased {
		fmt.Fprintf(b, "\t%s %q\n", imp.name, imp.path)
	}
	b.WriteString(")\n\n")
}

func genComponent(b *bytes.Buffer, c *ast.Component, resolved map[ast.Node]types.Type, table filterTable, structFields, nodeProps map[string]map[string]bool, imports map[string]bool, fset *token.FileSet, cls *attrclass.Classifier, bag *diag.Bag) bool {
	params, err := parseParams(c.Params)
	if err != nil {
		bag.Errorf(c.Pos(), c.End(), "invalid-syntax", "%s", strings.TrimPrefix(err.Error(), "codegen: "))
		return false
	}
	if err := checkReservedParams(params); err != nil {
		bag.Errorf(c.Pos(), c.End(), "reserved-param", "%s", strings.TrimPrefix(err.Error(), "codegen: "))
		return false
	}

	// A method component (non-empty Recv) emits a Go method whose receiver var is
	// in scope in the body (so `{p.Field}` works); its props struct (if any) is
	// named <RecvTypeName><Name>Props, and the receiver clause is emitted verbatim
	// in the signature. A free function component has no receiver: props struct
	// <Name>Props and a plain `func <Name>`.
	propsName := c.Name + "Props"
	// recvVar/recvTypeName stay "" for a function component; for a method component
	// they are threaded into genNode → genChildComponent so a dotted child tag whose
	// left == recvVar lowers to a method call.
	var recvVar, recvTypeName string
	if c.Recv != "" {
		var rerr error
		recvVar, _, recvTypeName, rerr = parseRecv(c.Recv)
		if rerr != nil {
			bag.Errorf(c.Pos(), c.End(), "invalid-recv", "%s", strings.TrimPrefix(rerr.Error(), "codegen: "))
			return false
		}
		if rerr := checkReservedRecvVar(recvVar); rerr != nil {
			bag.Errorf(c.Pos(), c.End(), "reserved-recv", "%s", strings.TrimPrefix(rerr.Error(), "codegen: "))
			return false
		}
		propsName = recvTypeName + c.Name + "Props"
	}

	// Props struct (field types are syntactic — straight from the param list).
	// When the body references `{children}`, synthesize an implicit
	// `Children gsx.Node` slot field after the param fields; the parent fills it
	// with a render closure (genChildComponent). A NULLARY METHOD (no params, no
	// children) gets NO props struct and NO _gsxp param — `p.Page()`. A nullary
	// FUNCTION component keeps its empty props struct (`Page(PageProps{})`), since
	// the child-component invocation path (genChildComponent) always builds a
	// `<Tag>Props{}` literal.
	hasChildren := usesChildren(c.Body)
	// A single-root component is fallthrough-eligible: it synthesizes an
	// `Attrs gsx.Attrs` props field the caller fills with undeclared attributes,
	// applied (class-merge + spread) at the root element below. Mirror the
	// `Children` synthesis exactly — gate into hasProps, append AFTER the param
	// and Children fields (field order: params, Children, Attrs).
	root, hasRoot := singleRoot(c.Body)
	// MANUAL mode: a component whose body references the identifier `attrs` (a
	// `{...attrs}` element spread, or `attrs.X()` in an interp/expr/clause) takes
	// over fallthrough placement itself — auto root injection is DISABLED and the
	// author's `{...attrs}` renders the bag. It is ALWAYS fallthrough-eligible
	// (forces the Attrs field), even for a nullary method (which then gains a props
	// struct — correct, since it has fallthrough). See usesAttrs.
	manual := usesAttrs(c.Body)
	// A NULLARY method component (no params, no children) is invoked bare as
	// `p.Page()` with no props struct (the call-site nullary contract), so it must
	// NOT gain a props struct via AUTO fallthrough — gate auto out of that case.
	// A function component (always has a props struct) or a method with params/
	// children is auto-eligible; manual forces eligibility regardless.
	autoEligible := hasRoot && (c.Recv == "" || len(params) > 0 || hasChildren)
	hasFallthrough := autoEligible || manual
	// AUTO application (Task-1 root class-merge + spread injection) happens only for
	// a single-root component that is auto-eligible (so the Attrs FIELD exists — a
	// nullary method with no props struct is NOT) and does NOT reference `attrs`.
	// When manual, the root (and whole body) emits via normal genNode and the author
	// places the bag; the bag is bound to the `attrs` local below.
	autoApply := autoEligible && !manual
	hasProps := c.Recv == "" || len(params) > 0 || hasChildren || hasFallthrough
	if hasProps {
		fmt.Fprintf(b, "type %s struct {\n", propsName)
		for _, p := range params {
			fmt.Fprintf(b, "\t%s %s\n", fieldName(p.name), p.typ)
		}
		if hasChildren {
			b.WriteString("\tChildren gsx.Node\n")
		}
		if hasFallthrough {
			b.WriteString("\tAttrs gsx.Attrs\n")
		}
		fmt.Fprintf(b, "}\n\n")
	}

	// Render func/method. The only differences between function and method
	// components are the signature (receiver clause + props-struct name) and
	// whether a props struct exists; the render-closure body is identical.
	if c.Recv != "" {
		fmt.Fprintf(b, "func %s %s(", c.Recv, c.Name)
	} else {
		fmt.Fprintf(b, "func %s(", c.Name)
	}
	if hasProps {
		fmt.Fprintf(b, "_gsxp %s", propsName)
	}
	b.WriteString(") gsx.Node {\n")

	// Bind each USED param to a same-named local so interpolation expressions can
	// be emitted verbatim. The props param, io.Writer closure param, and
	// gsx.Writer local use the reserved _gsx* namespace so a user param named
	// p/w/gw cannot collide with them. ctx stays ambient (user interpolation exprs
	// may reference it). For a method component the receiver var is already in
	// scope (it's the method receiver) and is NOT bound as a prop local.
	b.WriteString("\treturn gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {\n")
	used := usedParams(c, params)
	for _, p := range params {
		if used[p.name] {
			fmt.Fprintf(b, "\t\t%s := _gsxp.%s\n", p.name, fieldName(p.name))
		}
	}
	if hasChildren {
		// Bind the implicit slot local; the bare `{children}` interp resolves to
		// this gsx.Node and renders via the catNode path (gw.Node, nil-safe).
		b.WriteString("\t\tchildren := _gsxp.Children\n")
	}
	if manual {
		// MANUAL mode: bind the synthesized bag to a same-named local so the author's
		// `{...attrs}` element spread (emitted as `gw.Spread(ctx, attrs)`) and any
		// `attrs.X()` reference resolve. Nil-safe: a nil bag spreads/queries to
		// nothing. (`_ = attrs` guards the unlikely case where usesAttrs detected a
		// reference the body no longer reaches after lowering.)
		b.WriteString("\t\tattrs := _gsxp.Attrs\n\t\t_ = attrs\n")
	}
	b.WriteString("\t\t_gsxgw := gsx.W(_gsxw)\n")
	for _, m := range c.Body {
		// The single root (when AUTO-eligible) is emitted via the fallthrough path so
		// the bag's class merges + the rest spreads at the root; all other body nodes
		// (insignificant whitespace/comments) render normally. In MANUAL mode autoApply
		// is false, so the root emits via normal genNode and the author's {...attrs}
		// places the bag.
		if autoApply && m == ast.Markup(root) {
			if !emitRootElement(b, root, resolved, table, structFields, nodeProps, imports, fset, recvVar, recvTypeName, cls, bag) {
				return false
			}
			continue
		}
		if !genNode(b, m, resolved, table, structFields, nodeProps, imports, fset, recvVar, recvTypeName, cls, bag) {
			return false
		}
	}
	b.WriteString("\t\treturn _gsxgw.Err()\n")
	b.WriteString("\t})\n}\n\n")
	return true
}

// emitRootElement emits a single-root element with CALLER-WINS attribute
// fallthrough applied: the bag (`_gsxp.Attrs`) merges its class into the root's
// class (last-wins → caller-wins) and merges its style over the root's style
// (property last-wins → caller-wins), and every OTHER root attr is emitted under
// a runtime guard (`if !_gsxp.Attrs.Has(name)`) so a bag entry of the same name
// SHADOWS it — the guarded attr is skipped and the bag's value spreads instead
// (caller-wins, D5 flipped). Each guarded attr keeps its own context escaper
// (gw.URL / gw.JSValAttr / gw.AttrValue …) since its body is exactly the normal
// emitAttr output. The root's CHILDREN render via normal genNode — the bag does
// NOT propagate. When the bag is nil/empty, every guard is true (Has is nil-safe),
// ClassMerged/StyleMerged add nothing, and Spread(empty) writes nothing — so the
// output is byte-equivalent to the normal Element path.
//
// A void root cannot receive fallthrough (it has no place for it to matter beyond
// attrs, but void roots ARE handled: class/style-merge + guarded attrs + spread
// then `/>`).
func emitRootElement(b *bytes.Buffer, el *ast.Element, resolved map[ast.Node]types.Type, table filterTable, structFields, nodeProps map[string]map[string]bool, imports map[string]bool, fset *token.FileSet, recvVar, recvTypeName string, cls *attrclass.Classifier, bag *diag.Bag) bool {
	emitLine(b, fset, el.Pos())
	emitS(b, "<"+el.Tag)
	// AUTO mode: there is no author `{...attrs}`, so the bag spreads at the END and
	// every root attr is overridable. splitIdx == len(el.Attrs) means "all attrs
	// precede the (synthetic) spread" → all guarded.
	if !emitFallthroughAttrs(b, el.Attrs, len(el.Attrs), resolved, table, imports, cls, bag) {
		return false
	}
	if el.Void {
		emitS(b, "/>")
		return true
	}
	emitS(b, ">")
	if strings.EqualFold(el.Tag, "style") {
		for _, c := range el.Children {
			if !genStyleChild(b, c, resolved, imports, fset, bag) {
				return false
			}
		}
	} else if strings.EqualFold(el.Tag, "script") {
		for _, c := range el.Children {
			if !genScriptChild(b, c, resolved, imports, fset, bag) {
				return false
			}
		}
	} else {
		for _, c := range el.Children {
			if !genNode(b, c, resolved, table, structFields, nodeProps, imports, fset, recvVar, recvTypeName, cls, bag) {
				return false
			}
		}
	}
	emitS(b, "</"+el.Tag+">")
	return true
}

// emitFallthroughAttrs emits the caller-wins attribute section (between `<tag`
// and the closing `>` / `/>`) shared by AUTO mode (emitRootElement) and MANUAL
// mode (emitManualSpreadElement). splitIdx is the index in attrs at which the
// bag spreads:
//   - AUTO mode: splitIdx == len(attrs) — the (synthetic) bag spread is at the
//     end, so EVERY scalar root attr is OVERRIDABLE (guarded `if !Has(name)`,
//     caller-wins).
//   - MANUAL mode: splitIdx is the position of the author's `{...attrs}` — scalar
//     attrs BEFORE it are overridable (guarded); scalar attrs AFTER it are FORCED
//     (emitted UNGUARDED so the root always wins) and their names are excluded
//     from the bag spread so a same-named bag entry can never emit (root wins).
//
// class/style are positional-exempt: wherever they appear they MERGE caller-last
// (ClassMerged / StyleMerged), emitted once at the spread position. The author's
// `{...attrs}` SpreadAttr itself (when present at splitIdx) is consumed here, not
// emitted via emitAttr.
func emitFallthroughAttrs(b *bytes.Buffer, attrs []ast.Attr, splitIdx int, resolved map[ast.Node]types.Type, table filterTable, imports map[string]bool, cls *attrclass.Classifier, bag *diag.Bag) bool {
	// Find a composed/static class attr to merge the bag's class into, and a
	// composed/static style attr whose declarations the bag's style merges over.
	var classAttr *ast.ClassAttr    // composed class={ … }
	var staticClass *ast.StaticAttr // static class="x"
	var styleAttr *ast.ClassAttr    // composed style={ … } (CtxCSS ClassAttr)
	var staticStyle *ast.StaticAttr // static style="x"
	for _, a := range attrs {
		switch t := a.(type) {
		case *ast.ClassAttr:
			switch t.Name {
			case "class":
				classAttr = t
			case "style":
				styleAttr = t
			}
		case *ast.StaticAttr:
			switch t.Name {
			case "class":
				staticClass = t
			case "style":
				staticStyle = t
			}
		}
	}
	// forcedNames collects the names of post-spread scalar attrs (MANUAL mode) so
	// the bag spread drops them — the unguarded root emit then wins.
	var forcedNames []string

	// emitScalar emits one non-class/style attr, either guarded (overridable) or
	// unguarded (forced).
	emitScalar := func(a ast.Attr, guarded bool) bool {
		name, ok := rootAttrName(a)
		if !ok {
			// No single static name (Cond) — no caller-wins shadow target; emit
			// unguarded. (A SpreadAttr at the split position is consumed below, not
			// here.)
			return emitAttr(b, a, resolved, table, imports, cls, bag)
		}
		if !guarded {
			forcedNames = append(forcedNames, name)
			return emitAttr(b, a, resolved, table, imports, cls, bag)
		}
		fmt.Fprintf(b, "\t\tif !_gsxp.Attrs.Has(%s) {\n", strconv.Quote(name))
		if !emitAttr(b, a, resolved, table, imports, cls, bag) {
			return false
		}
		b.WriteString("\t\t}\n")
		return true
	}

	// emitSpread emits the class merge, style merge, then the bag spread (dropping
	// class/style + any forced names). Called once, at the split position.
	emitSpread := func() bool {
		// If the root had NO class attr at all, emit a merged class in attr position —
		// writes class only when the bag contributes a non-empty token set.
		if classAttr == nil && staticClass == nil {
			b.WriteString("\t\t_gsxgw.ClassMerged(_gsxp.Attrs.Class())\n")
		}
		// Style: when the caller set a `style`, merge it OVER the root's style
		// property-last-wins (StyleMerged, caller-wins). When the caller did NOT set a
		// style, emit the root's own style via its normal context path UNCHANGED — this
		// preserves the composable-style CSS sanitizer (gw.Style → the ZgotmplZ failsafe
		// for an injection, and intra-style duplicate properties) which StyleMerged's
		// `prop: value` parser would lose (it drops colon-less fragments and dedupes
		// properties). The empty-bag case takes the else branch → byte-identical output.
		if styleAttr != nil || staticStyle != nil {
			b.WriteString("\t\tif _gsxp.Attrs.Has(\"style\") {\n")
			fmt.Fprintf(b, "\t\t\t_gsxgw.StyleMerged(%s, _gsxp.Attrs.Style())\n", rootStyleString(styleAttr, staticStyle))
			b.WriteString("\t\t} else {\n")
			if staticStyle != nil {
				if !emitAttr(b, staticStyle, resolved, table, imports, cls, bag) {
					return false
				}
			} else {
				emitStyleAttr(b, styleAttr)
			}
			b.WriteString("\t\t}\n")
		} else {
			// No root style: emit StyleMerged so a caller-only style still appears (it is
			// a no-op when the bag has no style either).
			b.WriteString("\t\t_gsxgw.StyleMerged(\"\", _gsxp.Attrs.Style())\n")
		}
		// Spread the rest of the bag, dropping class/style (both merged above) plus
		// any forced names (excluded so the unguarded root emit wins — caller can't
		// override a post-spread attr). Every other bag attr spreads, including one
		// that shadows a guarded (overridable) root attr (which was then skipped).
		without := append([]string{"class", "style"}, forcedNames...)
		quoted := make([]string, len(without))
		for i, n := range without {
			quoted[i] = strconv.Quote(n)
		}
		fmt.Fprintf(b, "\t\t_gsxgw.Spread(ctx, _gsxp.Attrs.Without(%s))\n", strings.Join(quoted, ", "))
		return true
	}

	// In MANUAL mode the author's `{...attrs}` lives at splitIdx; collecting the
	// forced names requires emitting post-spread scalars BEFORE the spread call (so
	// forcedNames is populated). We therefore emit in three phases:
	//   1. overridable scalars (idx < splitIdx, guarded)
	//   2. forced scalars (idx > splitIdx, unguarded, names collected)
	//   3. the spread (class/style merge + bag, dropping the forced names)
	// then re-walk to interleave nothing else — class/style are handled by phase 3.
	// Emission order in the output: overridable scalars, then the spread, then the
	// forced scalars — matching `<div a {...attrs} b/>` (a, bag, b). We achieve that
	// by buffering the forced-scalar bytes.
	var forcedBuf bytes.Buffer
	for i, a := range attrs {
		// class is merged in place here (emitRoot{Composed,Static}Class); style is
		// skipped here and merged by emitSpread (phase 3). Both ignore spread position.
		switch t := a.(type) {
		case *ast.ClassAttr:
			if t == classAttr {
				emitRootComposedClass(b, t)
				continue
			}
			if t == styleAttr {
				continue
			}
		case *ast.StaticAttr:
			if t == staticClass {
				emitRootStaticClass(b, t)
				continue
			}
			if t == staticStyle {
				continue
			}
		case *ast.SpreadAttr:
			// The bag spread at the split position is consumed here. A non-bag spread
			// (handled by the caller's detection) never reaches this helper at splitIdx;
			// a stray SpreadAttr at any other index is emitted inline (unchanged).
			if i == splitIdx {
				continue
			}
			fmt.Fprintf(b, "\t\t_gsxgw.Spread(ctx, %s)\n", strings.TrimSpace(t.Expr))
			continue
		}
		if i < splitIdx {
			if !emitScalar(a, true) {
				return false
			}
			continue
		}
		// Post-spread: forced. Buffer it (emitted after the spread) but collect its
		// name now via emitScalar against forcedBuf.
		saved := b
		b = &forcedBuf
		okScalar := emitScalar(a, false)
		b = saved
		if !okScalar {
			return false
		}
	}
	// Phase 3: the spread (now that forcedNames is fully populated), then flush the
	// buffered forced scalars after it.
	if !emitSpread() {
		return false
	}
	b.Write(forcedBuf.Bytes())
	return true
}

// emitManualSpreadElement emits a non-component element that carries the author's
// `{...attrs}` bag spread (MANUAL fallthrough), applying positional precedence:
// root attrs before the spread are caller-overridable, attrs after are forced
// (root wins). splitIdx is the bag SpreadAttr's index in el.Attrs (guaranteed
// unique by the caller).
func emitManualSpreadElement(b *bytes.Buffer, el *ast.Element, splitIdx int, resolved map[ast.Node]types.Type, table filterTable, structFields, nodeProps map[string]map[string]bool, imports map[string]bool, fset *token.FileSet, recvVar, recvTypeName string, cls *attrclass.Classifier, bag *diag.Bag) bool {
	emitS(b, "<"+el.Tag)
	if !emitFallthroughAttrs(b, el.Attrs, splitIdx, resolved, table, imports, cls, bag) {
		return false
	}
	if el.Void {
		emitS(b, "/>")
		return true
	}
	emitS(b, ">")
	if strings.EqualFold(el.Tag, "style") {
		for _, c := range el.Children {
			if !genStyleChild(b, c, resolved, imports, fset, bag) {
				return false
			}
		}
	} else if strings.EqualFold(el.Tag, "script") {
		for _, c := range el.Children {
			if !genScriptChild(b, c, resolved, imports, fset, bag) {
				return false
			}
		}
	} else {
		for _, c := range el.Children {
			if !genNode(b, c, resolved, table, structFields, nodeProps, imports, fset, recvVar, recvTypeName, cls, bag) {
				return false
			}
		}
	}
	emitS(b, "</"+el.Tag+">")
	return true
}

// bagSpreadIndex returns the index of the author's `{...attrs}` bag spread in
// attrs (a SpreadAttr whose trimmed Expr is the bound bag name "attrs"), whether
// one was found, and an error if more than one is present (precedence ambiguous).
// A non-bag spread (`{...someOtherExpr}`) is ignored — it keeps its inline emit.
func bagSpreadIndex(attrs []ast.Attr) (int, bool, error) {
	idx, found := -1, false
	for i, a := range attrs {
		s, ok := a.(*ast.SpreadAttr)
		if !ok || strings.TrimSpace(s.Expr) != "attrs" {
			continue
		}
		if found {
			return 0, false, fmt.Errorf("codegen: more than one {...attrs} spread on an element; precedence is ambiguous")
		}
		idx, found = i, true
	}
	return idx, found, nil
}

// emitRootComposedClass emits a composed `class={ … }` merged with the bag's
// class: ` class="` + gw.Class(<existing parts…>, gsx.Class(_gsxp.Attrs.Class()))
// + `"`. Mirrors emitClassAttr's part lowering, appending the bag class as a
// final unconditional part so it merges/dedupes through ClassMerger.
func emitRootComposedClass(b *bytes.Buffer, a *ast.ClassAttr) {
	parts := make([]string, 0, len(a.Parts)+1)
	for _, p := range a.Parts {
		if p.Cond == "" {
			parts = append(parts, fmt.Sprintf("gsx.Class(%s)", strings.TrimSpace(p.Expr)))
		} else {
			parts = append(parts, fmt.Sprintf("gsx.ClassIf(%s, %s)", strings.TrimSpace(p.Expr), strings.TrimSpace(p.Cond)))
		}
	}
	parts = append(parts, "gsx.Class(_gsxp.Attrs.Class())")
	fmt.Fprintf(b, "\t\t_gsxgw.S(%s)\n", strconv.Quote(" "+a.Name+`="`))
	fmt.Fprintf(b, "\t\t_gsxgw.Class(%s)\n", strings.Join(parts, ", "))
	fmt.Fprintf(b, "\t\t_gsxgw.S(%s)\n", strconv.Quote(`"`))
}

// emitRootStaticClass emits a static `class="x"` merged with the bag's class:
// ` class="` + gw.Class(gsx.Class("x"), gsx.Class(_gsxp.Attrs.Class())) + `"`.
func emitRootStaticClass(b *bytes.Buffer, a *ast.StaticAttr) {
	fmt.Fprintf(b, "\t\t_gsxgw.S(%s)\n", strconv.Quote(" "+a.Name+`="`))
	fmt.Fprintf(b, "\t\t_gsxgw.Class(gsx.Class(%s), gsx.Class(_gsxp.Attrs.Class()))\n", strconv.Quote(a.Value))
	fmt.Fprintf(b, "\t\t_gsxgw.S(%s)\n", strconv.Quote(`"`))
}

// rootAttrName returns the single static attribute name of a non-class/style root
// attr that the caller-wins guard brackets. Static/bool/expr/JS attrs each have
// one name; Spread/Cond attrs have none (ok=false), so they emit unguarded.
func rootAttrName(a ast.Attr) (string, bool) {
	switch t := a.(type) {
	case *ast.StaticAttr:
		return t.Name, true
	case *ast.BoolAttr:
		return t.Name, true
	case *ast.ExprAttr:
		return t.Name, true
	case *ast.JSAttr:
		return t.Name, true
	}
	return "", false
}

// rootStyleString returns the Go expression for the root element's own style
// declarations, passed as StyleMerged's first arg (the bag's Style() is second,
// caller-wins). For a static `style="x"` it is the quoted literal; for a composed
// `style={ … }` (a CtxCSS ClassAttr) it is a gsx.StyleString(parts…) call mirroring
// emitStyleAttr's part lowering (string-literal parts trusted, dynamic parts
// CSS-value-filtered). With no style attr it is the empty string literal.
func rootStyleString(styleAttr *ast.ClassAttr, staticStyle *ast.StaticAttr) string {
	switch {
	case staticStyle != nil:
		return strconv.Quote(staticStyle.Value)
	case styleAttr != nil:
		parts := make([]string, 0, len(styleAttr.Parts))
		for _, p := range styleAttr.Parts {
			val := styleDeclExpr(p.Expr)
			if p.Cond == "" {
				parts = append(parts, fmt.Sprintf("gsx.Class(%s)", val))
			} else {
				parts = append(parts, fmt.Sprintf("gsx.ClassIf(%s, %s)", val, strings.TrimSpace(p.Cond)))
			}
		}
		return "gsx.StyleString(" + strings.Join(parts, ", ") + ")"
	default:
		return `""`
	}
}

// genNode emits one markup node. recvVar/recvTypeName are the enclosing
// component's receiver var + type name (empty for a function component); they
// thread down to genChildComponent for the method-vs-package disambiguation of a
// dotted child-component tag.
func genNode(b *bytes.Buffer, n ast.Markup, resolved map[ast.Node]types.Type, table filterTable, structFields, nodeProps map[string]map[string]bool, imports map[string]bool, fset *token.FileSet, recvVar, recvTypeName string, cls *attrclass.Classifier, bag *diag.Bag) bool {
	switch t := n.(type) {
	case *ast.Text:
		emitS(b, t.Value)
	case *ast.Doctype:
		// Renders verbatim — Text holds the full `<!DOCTYPE …>` source.
		emitS(b, t.Text)
	case *ast.Element:
		emitLine(b, fset, t.Pos())
		if isComponentTag(t.Tag) {
			return genChildComponent(b, t, resolved, table, structFields, nodeProps, imports, fset, recvVar, recvTypeName, cls, bag)
		}
		// MANUAL fallthrough: an element carrying the author's `{...attrs}` bag spread
		// gets position-aware precedence (pre-spread overridable, post-spread forced).
		// Detection is the trimmed SpreadAttr Expr == bound bag name "attrs"; a non-bag
		// spread keeps its inline emit via the normal attr loop below.
		if splitIdx, found, err := bagSpreadIndex(t.Attrs); err != nil {
			bag.Errorf(t.Pos(), t.End(), "attr-fallthrough", "%s", strings.TrimPrefix(err.Error(), "codegen: "))
			return false
		} else if found {
			return emitManualSpreadElement(b, t, splitIdx, resolved, table, structFields, nodeProps, imports, fset, recvVar, recvTypeName, cls, bag)
		}
		emitS(b, "<"+t.Tag)
		for _, a := range t.Attrs {
			if !emitAttr(b, a, resolved, table, imports, cls, bag) {
				return false
			}
		}
		if t.Void {
			emitS(b, "/>")
			return true
		}
		emitS(b, ">")
		if strings.EqualFold(t.Tag, "style") {
			for _, c := range t.Children {
				if !genStyleChild(b, c, resolved, imports, fset, bag) {
					return false
				}
			}
		} else if strings.EqualFold(t.Tag, "script") {
			for _, c := range t.Children {
				if !genScriptChild(b, c, resolved, imports, fset, bag) {
					return false
				}
			}
		} else {
			for _, c := range t.Children {
				if !genNode(b, c, resolved, table, structFields, nodeProps, imports, fset, recvVar, recvTypeName, cls, bag) {
					return false
				}
			}
		}
		emitS(b, "</"+t.Tag+">")
	case *ast.Interp:
		return genInterp(b, t, resolved, table, imports, fset, bag)
	case *ast.Fragment:
		for _, c := range t.Children {
			if !genNode(b, c, resolved, table, structFields, nodeProps, imports, fset, recvVar, recvTypeName, cls, bag) {
				return false
			}
		}
	case *ast.ForMarkup:
		emitLine(b, fset, t.Pos())
		fmt.Fprintf(b, "for %s {\n", t.Clause)
		for _, c := range t.Body {
			if !genNode(b, c, resolved, table, structFields, nodeProps, imports, fset, recvVar, recvTypeName, cls, bag) {
				return false
			}
		}
		b.WriteString("}\n")
	case *ast.IfMarkup:
		emitLine(b, fset, t.Pos())
		fmt.Fprintf(b, "if %s {\n", t.Cond)
		for _, c := range t.Then {
			if !genNode(b, c, resolved, table, structFields, nodeProps, imports, fset, recvVar, recvTypeName, cls, bag) {
				return false
			}
		}
		b.WriteString("}")
		if t.Else != nil {
			b.WriteString(" else {\n")
			for _, c := range t.Else {
				if !genNode(b, c, resolved, table, structFields, nodeProps, imports, fset, recvVar, recvTypeName, cls, bag) {
					return false
				}
			}
			b.WriteString("}")
		}
		b.WriteString("\n")
	case *ast.SwitchMarkup:
		emitLine(b, fset, t.Pos())
		fmt.Fprintf(b, "switch %s {\n", t.Tag)
		for _, cc := range t.Cases {
			if cc.Default {
				b.WriteString("default:\n")
			} else {
				fmt.Fprintf(b, "case %s:\n", cc.List)
			}
			for _, c := range cc.Body {
				if !genNode(b, c, resolved, table, structFields, nodeProps, imports, fset, recvVar, recvTypeName, cls, bag) {
					return false
				}
			}
		}
		b.WriteString("}\n")
	case *ast.GoBlock:
		emitLine(b, fset, t.Pos())
		b.WriteString(t.Code)
		b.WriteString("\n")
	default:
		bag.Errorf(n.Pos(), n.End(), "unsupported-node", "unsupported markup node %T", n)
		return false
	}
	return true
}

// genInterp emits the type-aware writer call for an interpolation. The type comes
// from the go/types resolution pass; the expression is emitted verbatim (params
// are in scope as locals).
func genInterp(b *bytes.Buffer, n *ast.Interp, resolved map[ast.Node]types.Type, table filterTable, imports map[string]bool, fset *token.FileSet, bag *diag.Bag) bool {
	emitLine(b, fset, n.Pos())
	if len(n.Stages) > 0 {
		// Lower the pipeline to nested filter calls — the SAME lowerPipe output the
		// probe used, so resolved[n] is already the pipeline's RESULT type. Record
		// each used filter package path so writeImports emits it under its alias.
		lowered, usedPkgs, err := lowerPipe(n.Expr, n.Stages, table)
		if err != nil {
			bag.Errorf(n.Pos(), n.End(), "unresolved-pipeline", "%s", strings.TrimPrefix(err.Error(), "codegen: "))
			return false
		}
		for _, path := range usedPkgs {
			imports[path] = true
		}
		t, ok := resolved[n]
		if !ok || t == nil {
			bag.Errorf(n.Pos(), n.End(), "unresolved-pipeline", "could not resolve type of pipeline %q", n.Expr)
			return false
		}
		return emitRender(b, lowered, t, imports, n, bag)
	}
	if n.Try {
		bag.Errorf(n.Pos(), n.End(), "unsupported-try", "`?` try-marker not supported yet")
		return false
	}
	t, ok := resolved[n]
	if !ok || t == nil {
		bag.Errorf(n.Pos(), n.End(), "unresolved-interp", "could not resolve type of interpolation %q", n.Expr)
		return false
	}
	expr := strings.TrimSpace(n.Expr)
	if tup, ok := t.(*types.Tuple); ok {
		if tup.Len() != 2 || tup.At(1).Type().String() != "error" {
			bag.Errorf(n.Pos(), n.End(), "invalid-tuple", "interpolation %q returns %s; only (T, error) is supported", expr, t)
			return false
		}
		// v, err := expr; if err != nil { return err }; then render v by its type.
		tmp := fmt.Sprintf("_gsxv%d", interpTemp)
		interpTemp++
		fmt.Fprintf(b, "\t\t%s, _gsxerr := %s\n\t\tif _gsxerr != nil {\n\t\t\treturn _gsxerr\n\t\t}\n", tmp, expr)
		return emitRender(b, tmp, tup.At(0).Type(), imports, n, bag)
	}
	return emitRender(b, expr, t, imports, n, bag)
}

// interpTemp gives unique unwrap temp names within a generated file. It is reset
// at the start of generateFile.
var interpTemp int

// emitLine writes a //line directive mapping subsequent output to the gsx node's
// source position, so Go compiler errors point at the .gsx file. The directive
// must begin at column 1; it is written at the start of a line (the preceding
// writes always end in "\n") with no leading indentation. go/format special-cases
// //line comments and preserves them verbatim.
func emitLine(b *bytes.Buffer, fset *token.FileSet, pos token.Pos) {
	p := fset.Position(pos)
	fmt.Fprintf(b, "//line %s:%d:%d\n", filepath.Base(p.Filename), p.Line, p.Column)
}

// emitRender writes the type-aware writer call for a single renderable value
// named by expr (a verbatim expression or a temp identifier) and its type t.
// n is the AST node for positioning any error diagnostic.
func emitRender(b *bytes.Buffer, expr string, t types.Type, imports map[string]bool, n ast.Node, bag *diag.Bag) bool {
	switch classify(t) {
	case catString:
		fmt.Fprintf(b, "\t\t_gsxgw.Text(string(%s))\n", expr)
	case catBytes:
		fmt.Fprintf(b, "\t\t_gsxgw.Text(string(%s))\n", expr)
	case catInt:
		imports["strconv"] = true
		fmt.Fprintf(b, "\t\t_gsxgw.Text(strconv.FormatInt(int64(%s), 10))\n", expr)
	case catUint:
		imports["strconv"] = true
		fmt.Fprintf(b, "\t\t_gsxgw.Text(strconv.FormatUint(uint64(%s), 10))\n", expr)
	case catFloat:
		imports["strconv"] = true
		fmt.Fprintf(b, "\t\t_gsxgw.Text(strconv.FormatFloat(float64(%s), 'g', -1, 64))\n", expr)
	case catBool:
		imports["strconv"] = true
		fmt.Fprintf(b, "\t\t_gsxgw.Text(strconv.FormatBool(bool(%s)))\n", expr)
	case catStringer:
		fmt.Fprintf(b, "\t\t_gsxgw.Text((%s).String())\n", expr)
	case catNode:
		fmt.Fprintf(b, "\t\t_gsxgw.Node(ctx, %s)\n", expr)
	case catNodeSlice:
		fmt.Fprintf(b, "\t\tfor _, _gsxn := range %s {\n\t\t\t_gsxgw.Node(ctx, _gsxn)\n\t\t}\n", expr)
	default:
		bag.Errorf(n.Pos(), n.End(), "unrenderable", "interpolation %q has type %s; not a renderable type", expr, t)
		return false
	}
	return true
}

func emitS(b *bytes.Buffer, s string) {
	fmt.Fprintf(b, "\t\t_gsxgw.S(%s)\n", strconv.Quote(s))
}

// genStyleChild emits one child of a <style> element. Text is raw CSS (verbatim);
// an Interp is rendered in CSS context (auto-sanitized). <style> bodies contain
// only Text and @{ } interps (parser guarantee).
func genStyleChild(b *bytes.Buffer, n ast.Markup, resolved map[ast.Node]types.Type, imports map[string]bool, fset *token.FileSet, bag *diag.Bag) bool {
	switch t := n.(type) {
	case *ast.Text:
		emitS(b, t.Value)
		return true
	case *ast.Interp:
		return emitCSSInterp(b, t, resolved, imports, fset, bag)
	default:
		bag.Errorf(n.Pos(), n.End(), "unsupported-style-node", "<style> body may contain only text and @{ } interpolations, got %T", n)
		return false
	}
}

// emitCSSInterp renders a <style> interpolation value in CSS block context.
func emitCSSInterp(b *bytes.Buffer, n *ast.Interp, resolved map[ast.Node]types.Type, imports map[string]bool, fset *token.FileSet, bag *diag.Bag) bool {
	if n.Try {
		bag.Errorf(n.Pos(), n.End(), "unsupported-try", "`?` try-marker not supported in <style> interpolation yet")
		return false
	}
	if len(n.Stages) > 0 {
		bag.Errorf(n.Pos(), n.End(), "unresolved-pipeline", "pipeline stages not supported in <style> interpolation yet")
		return false
	}
	t, ok := resolved[n]
	if !ok || t == nil {
		bag.Errorf(n.Pos(), n.End(), "unresolved-interp", "could not resolve type of <style> interpolation %q", n.Expr)
		return false
	}
	expr := strings.TrimSpace(n.Expr)
	if tup, ok := t.(*types.Tuple); ok {
		if tup.Len() != 2 || tup.At(1).Type().String() != "error" {
			bag.Errorf(n.Pos(), n.End(), "invalid-tuple", "<style> interpolation %q returns %s; only (T, error) is supported", expr, t)
			return false
		}
		tmp := fmt.Sprintf("_gsxv%d", interpTemp)
		interpTemp++
		fmt.Fprintf(b, "\t\t%s, _gsxerr := %s\n\t\tif _gsxerr != nil {\n\t\t\treturn _gsxerr\n\t\t}\n", tmp, expr)
		return emitRenderCSS(b, tmp, tup.At(0).Type(), imports, n, bag)
	}
	return emitRenderCSS(b, expr, t, imports, n, bag)
}

// emitRenderCSS writes a value in CSS block context (inside <style>): RawCSS and
// numbers are emitted raw (safe by construction); strings/Stringers go through
// gw.CSS (the value-filter). n is the AST node for positioning any error diagnostic.
func emitRenderCSS(b *bytes.Buffer, expr string, t types.Type, imports map[string]bool, n ast.Node, bag *diag.Bag) bool {
	if isRawCSS(t) {
		fmt.Fprintf(b, "\t\t_gsxgw.S(string(%s))\n", expr)
		return true
	}
	switch classify(t) {
	case catInt:
		imports["strconv"] = true
		fmt.Fprintf(b, "\t\t_gsxgw.S(strconv.FormatInt(int64(%s), 10))\n", expr)
	case catUint:
		imports["strconv"] = true
		fmt.Fprintf(b, "\t\t_gsxgw.S(strconv.FormatUint(uint64(%s), 10))\n", expr)
	case catFloat:
		imports["strconv"] = true
		fmt.Fprintf(b, "\t\t_gsxgw.S(strconv.FormatFloat(float64(%s), 'g', -1, 64))\n", expr)
	case catString, catBytes:
		fmt.Fprintf(b, "\t\t_gsxgw.CSS(string(%s))\n", expr)
	case catStringer:
		fmt.Fprintf(b, "\t\t_gsxgw.CSS((%s).String())\n", expr)
	default:
		bag.Errorf(n.Pos(), n.End(), "unrenderable-css", "value of type %s not renderable in CSS context (need string/number/Stringer or gsx.RawCSS)", t)
		return false
	}
	return true
}

// genScriptChild emits one child of a <script> element. Text is raw JS
// (verbatim); an Interp is rendered through the JS escaper selected by its
// JSCtx (set by internal/jsx). Comment-context holes were already un-split to
// Text by jsx.ResolveScripts, so they arrive here as Text.
func genScriptChild(b *bytes.Buffer, n ast.Markup, resolved map[ast.Node]types.Type, imports map[string]bool, fset *token.FileSet, bag *diag.Bag) bool {
	switch t := n.(type) {
	case *ast.Text:
		emitS(b, t.Value)
		return true
	case *ast.Interp:
		return emitJSInterp(b, t, resolved, imports, fset, bag)
	default:
		bag.Errorf(n.Pos(), n.End(), "unsupported-script-node", "<script> body may contain only text and @{ } interpolations, got %T", n)
		return false
	}
}

// emitJSInterp renders a <script> interpolation value through the runtime JS
// escaper chosen by its JSCtx. It mirrors emitCSSInterp's Try/Stages rejection
// and (T, error) tuple unwrap.
func emitJSInterp(b *bytes.Buffer, n *ast.Interp, resolved map[ast.Node]types.Type, imports map[string]bool, fset *token.FileSet, bag *diag.Bag) bool {
	if n.Try {
		bag.Errorf(n.Pos(), n.End(), "unsupported-try", "`?` try-marker not supported in <script> interpolation yet")
		return false
	}
	if len(n.Stages) > 0 {
		bag.Errorf(n.Pos(), n.End(), "unresolved-pipeline", "pipeline stages not supported in <script> interpolation yet")
		return false
	}
	t, ok := resolved[n]
	if !ok || t == nil {
		bag.Errorf(n.Pos(), n.End(), "unresolved-interp", "could not resolve type of <script> interpolation %q", n.Expr)
		return false
	}
	expr := strings.TrimSpace(n.Expr)
	// Unwrap (T, error) exactly like emitCSSInterp.
	if tup, ok := t.(*types.Tuple); ok {
		if tup.Len() != 2 || tup.At(1).Type().String() != "error" {
			bag.Errorf(n.Pos(), n.End(), "invalid-tuple", "<script> interpolation %q returns %s; only (T, error) is supported", expr, t)
			return false
		}
		tmp := fmt.Sprintf("_gsxv%d", interpTemp)
		interpTemp++
		fmt.Fprintf(b, "\t\t%s, _gsxerr := %s\n\t\tif _gsxerr != nil {\n\t\t\treturn _gsxerr\n\t\t}\n", tmp, expr)
		return emitJSValue(b, n.JSCtx, tmp, tup.At(0).Type(), imports, n, bag)
	}
	return emitJSValue(b, n.JSCtx, expr, t, imports, n, bag)
}

// emitJSValue selects the runtime JS escaper by JS context. Value context goes
// through JSVal(any) (JSON-encode; gsx.RawJS passthrough is handled at runtime);
// string/template/regexp contexts go through the string-taking escapers.
// n is the AST node for positioning any error diagnostic.
func emitJSValue(b *bytes.Buffer, ctx ast.JSCtx, expr string, t types.Type, imports map[string]bool, n ast.Node, bag *diag.Bag) bool {
	switch ctx {
	case ast.JSCtxValue:
		// JSVal accepts any (JSON-encode); gsx.RawJS passthrough handled at runtime.
		// No type constraint — numbers, structs, slices, maps all JSON-encode.
		fmt.Fprintf(b, "\t\t_gsxgw.JSVal(%s)\n", expr)
		return true
	case ast.JSCtxString:
		return emitJSString(b, "JSStr", expr, t, n, bag)
	case ast.JSCtxTemplate:
		return emitJSString(b, "JSTmpl", expr, t, n, bag)
	case ast.JSCtxRegexp:
		return emitJSString(b, "JSRegexp", expr, t, n, bag)
	default:
		bag.Errorf(n.Pos(), n.End(), "unsafe-js-context", "<script> interpolation %q has no JS context (internal error: ResolveScripts not run?)", expr)
		return false
	}
}

// emitJSString emits a string-context JS escaper call (JSStr/JSTmpl/JSRegexp),
// which take a Go string. The value must be string-like.
// n is the AST node for positioning any error diagnostic.
func emitJSString(b *bytes.Buffer, method, expr string, t types.Type, n ast.Node, bag *diag.Bag) bool {
	switch classify(t) {
	case catString, catBytes:
		fmt.Fprintf(b, "\t\t_gsxgw.%s(string(%s))\n", method, expr)
	case catStringer:
		fmt.Fprintf(b, "\t\t_gsxgw.%s((%s).String())\n", method, expr)
	default:
		bag.Errorf(n.Pos(), n.End(), "unrenderable-js", "value of type %s not renderable in a JS string/template/regex context (need string or Stringer)", t)
		return false
	}
	return true
}

// emitAttr emits one element attribute. Static values are escaped at codegen and
// always double-quoted; bool attrs use gw.BoolAttr. Expr attrs are handled in a
// later task; the deferred attr kinds error clearly.
func emitAttr(b *bytes.Buffer, a ast.Attr, resolved map[ast.Node]types.Type, table filterTable, imports map[string]bool, cls *attrclass.Classifier, bag *diag.Bag) bool {
	switch t := a.(type) {
	case *ast.StaticAttr:
		fmt.Fprintf(b, "\t\t_gsxgw.S(%s)\n", strconv.Quote(" "+t.Name+`="`+htmlAttrEscape(t.Value)+`"`))
	case *ast.BoolAttr:
		fmt.Fprintf(b, "\t\t_gsxgw.BoolAttr(%s, true)\n", strconv.Quote(t.Name))
	case *ast.ExprAttr:
		return emitExprAttr(b, t, resolved, table, imports, cls, bag)
	case *ast.JSAttr:
		return emitJSAttr(b, t, resolved, imports, bag)
	case *ast.ClassAttr:
		// class -> token merge (gw.Class); style -> '; '-joined declarations
		// (gw.Style) with dynamic parts CSS-value-filtered.
		if cls.Context(t.Name) == attrclass.CtxCSS {
			emitStyleAttr(b, t)
		} else {
			emitClassAttr(b, t)
		}
	case *ast.SpreadAttr:
		// emitAttr runs only for non-component elements (genNode routes component
		// tags to genChildComponent before the attr loop), so a SpreadAttr here is
		// always an element spread: gw.Spread writes the bag deterministically.
		// Note: gw.Spread entity-escapes values and drops invalid attr names, but
		// (per the gsx.Attrs trust contract) does NOT URL/CSS-sanitize or reject
		// JS-context keys — a bag's keys/values are trusted developer input. This is
		// deliberately distinct from the composable-style/expr-attr paths, which fail
		// closed on CSS/JS contexts because their values may be untrusted data.
		fmt.Fprintf(b, "\t\t_gsxgw.Spread(ctx, %s)\n", strings.TrimSpace(t.Expr))
	case *ast.CondAttr:
		// Attr emission is a sequence of writer calls between `<tag` and `>`, so
		// wrapping the branch's attr emits in a real Go `if`/`else` is valid. An
		// else-if is a *CondAttr in Else, handled by the recursive emitAttr below.
		// (No //line for the cond: emitAttr has no fset, the wrapper is a pure
		// control construct, and each nested attr emit carries its own line map.)
		fmt.Fprintf(b, "\t\tif %s {\n", t.Cond)
		for _, inner := range t.Then {
			if !emitAttr(b, inner, resolved, table, imports, cls, bag) {
				return false
			}
		}
		if len(t.Else) > 0 {
			b.WriteString("\t\t} else {\n")
			for _, inner := range t.Else {
				if !emitAttr(b, inner, resolved, table, imports, cls, bag) {
					return false
				}
			}
		}
		b.WriteString("\t\t}\n")
		return true
	default:
		bag.Errorf(a.Pos(), a.End(), "unsupported-attr", "unknown attribute %T", a)
		return false
	}
	return true
}

// emitJSAttr emits a JS-context attribute whose quoted value is literal JS with
// @{ } holes (form 2a, e.g. x-data="{ tab: @{ x } }"). Static JS text is
// HTML-attr-escaped at codegen so <,>,& survive the attribute; each hole is
// escaped by its JSCtx and then HTML-attr-escaped (the *Attr escapers do both).
func emitJSAttr(b *bytes.Buffer, a *ast.JSAttr, resolved map[ast.Node]types.Type, imports map[string]bool, bag *diag.Bag) bool {
	fmt.Fprintf(b, "\t\t_gsxgw.S(%s)\n", strconv.Quote(" "+a.Name+`="`))
	for _, seg := range a.Segments {
		switch s := seg.(type) {
		case *ast.Text:
			fmt.Fprintf(b, "\t\t_gsxgw.S(%s)\n", strconv.Quote(htmlAttrEscape(s.Value)))
		case *ast.Interp:
			if !emitJSAttrInterp(b, s, resolved, imports, bag) {
				return false
			}
		default:
			bag.Errorf(seg.Pos(), seg.End(), "unsupported-attr", "JS attribute %q value may contain only text and @{ } interpolations, got %T", a.Name, seg)
			return false
		}
	}
	fmt.Fprintf(b, "\t\t_gsxgw.S(%s)\n", strconv.Quote(`"`))
	return true
}

// emitJSAttrInterp renders one @{ } hole in a JS-context attribute value through
// the runtime *Attr escaper chosen by its JSCtx. It mirrors emitJSInterp's
// Try/Stages rejection and (T, error) tuple unwrap, but routes to the JS*Attr
// methods (which additionally HTML-attr-escape).
func emitJSAttrInterp(b *bytes.Buffer, n *ast.Interp, resolved map[ast.Node]types.Type, imports map[string]bool, bag *diag.Bag) bool {
	if n.Try {
		bag.Errorf(n.Pos(), n.End(), "unsupported-try", "`?` try-marker not supported in JS attribute interpolation yet")
		return false
	}
	if len(n.Stages) > 0 {
		bag.Errorf(n.Pos(), n.End(), "unresolved-pipeline", "pipeline stages not supported in JS attribute interpolation yet")
		return false
	}
	t, ok := resolved[n]
	if !ok || t == nil {
		bag.Errorf(n.Pos(), n.End(), "unresolved-interp", "could not resolve type of JS attribute interpolation %q", n.Expr)
		return false
	}
	expr := strings.TrimSpace(n.Expr)
	if tup, ok := t.(*types.Tuple); ok {
		if tup.Len() != 2 || tup.At(1).Type().String() != "error" {
			bag.Errorf(n.Pos(), n.End(), "invalid-tuple", "JS attribute interpolation %q returns %s; only (T, error) is supported", expr, t)
			return false
		}
		tmp := fmt.Sprintf("_gsxv%d", interpTemp)
		interpTemp++
		fmt.Fprintf(b, "\t\t%s, _gsxerr := %s\n\t\tif _gsxerr != nil {\n\t\t\treturn _gsxerr\n\t\t}\n", tmp, expr)
		return emitJSAttrValue(b, n.JSCtx, tmp, tup.At(0).Type(), n, bag)
	}
	return emitJSAttrValue(b, n.JSCtx, expr, t, n, bag)
}

// emitJSAttrValue selects the runtime JS *Attr escaper by JS context, mirroring
// emitJSValue but calling the attribute-escaping variants.
// n is the AST node for positioning any error diagnostic.
func emitJSAttrValue(b *bytes.Buffer, ctx ast.JSCtx, expr string, t types.Type, n ast.Node, bag *diag.Bag) bool {
	switch ctx {
	case ast.JSCtxValue:
		// JSValAttr accepts any (JSON-encode); gsx.RawJS passthrough at runtime.
		fmt.Fprintf(b, "\t\t_gsxgw.JSValAttr(%s)\n", expr)
		return true
	case ast.JSCtxString:
		return emitJSString(b, "JSStrAttr", expr, t, n, bag)
	case ast.JSCtxTemplate:
		return emitJSString(b, "JSTmplAttr", expr, t, n, bag)
	case ast.JSCtxRegexp:
		return emitJSString(b, "JSRegexpAttr", expr, t, n, bag)
	default:
		bag.Errorf(n.Pos(), n.End(), "unsafe-js-context", "JS attribute interpolation %q has no JS context (internal error: ResolveJSAttr not run?)", expr)
		return false
	}
}

// emitClassAttr lowers a composable `class={ … }` to the open ` class="`, a
// gw.Class call composing each part (gsx.Class for an unconditional Expr,
// gsx.ClassIf for a conditional one), and the closing `"`. gw.Class runs the
// tokens through the installed ClassMerger and writes the attr-escaped value.
func emitClassAttr(b *bytes.Buffer, a *ast.ClassAttr) {
	parts := make([]string, 0, len(a.Parts))
	for _, p := range a.Parts {
		if p.Cond == "" {
			parts = append(parts, fmt.Sprintf("gsx.Class(%s)", strings.TrimSpace(p.Expr)))
		} else {
			parts = append(parts, fmt.Sprintf("gsx.ClassIf(%s, %s)", strings.TrimSpace(p.Expr), strings.TrimSpace(p.Cond)))
		}
	}
	fmt.Fprintf(b, "\t\t_gsxgw.S(%s)\n", strconv.Quote(" "+a.Name+`="`))
	fmt.Fprintf(b, "\t\t_gsxgw.Class(%s)\n", strings.Join(parts, ", "))
	fmt.Fprintf(b, "\t\t_gsxgw.S(%s)\n", strconv.Quote(`"`))
}

// emitStyleAttr lowers a composable `style={ … }` to ` style="` + a gw.Style call
// composing each part as a CSS declaration, then `"`. A string-literal part is
// trusted and emitted raw; any dynamic part value is wrapped in gsx.FilterCSS so
// untrusted data cannot inject declarations or break out. gw.Style joins the
// included parts with "; " and attr-escapes the result.
func emitStyleAttr(b *bytes.Buffer, a *ast.ClassAttr) {
	parts := make([]string, 0, len(a.Parts))
	for _, p := range a.Parts {
		val := styleDeclExpr(p.Expr)
		if p.Cond == "" {
			parts = append(parts, fmt.Sprintf("gsx.Class(%s)", val))
		} else {
			parts = append(parts, fmt.Sprintf("gsx.ClassIf(%s, %s)", val, strings.TrimSpace(p.Cond)))
		}
	}
	fmt.Fprintf(b, "\t\t_gsxgw.S(%s)\n", strconv.Quote(" "+a.Name+`="`))
	fmt.Fprintf(b, "\t\t_gsxgw.Style(%s)\n", strings.Join(parts, ", "))
	fmt.Fprintf(b, "\t\t_gsxgw.S(%s)\n", strconv.Quote(`"`))
}

// styleDeclExpr returns the Go expression for a composed-style part's value: a
// pure string-literal part is trusted (returned verbatim); any other (dynamic)
// part is wrapped in gsx.FilterCSS so its runtime value is CSS-value-filtered.
func styleDeclExpr(expr string) string {
	e := strings.TrimSpace(expr)
	if isStringLiteralExpr(e) {
		return e
	}
	return "gsx.StyleValue(" + e + ")"
}

// isStringLiteralExpr reports whether expr is exactly a Go string literal.
func isStringLiteralExpr(expr string) bool {
	node, err := goparser.ParseExpr(expr)
	if err != nil {
		return false
	}
	lit, ok := node.(*goast.BasicLit)
	return ok && lit.Kind == token.STRING
}

// htmlAttrEscape escapes a static attribute value for a double-quoted context at
// codegen time (matches the runtime gw.AttrValue entity set).
func htmlAttrEscape(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", `"`, "&#34;", "'", "&#39;")
	return r.Replace(s)
}

// emitExprAttr emits an expr attribute value with context-aware escaping. A CSS
// context is contextually sanitized (gw.CSS) with a gsx.RawCSS author opt-out; a
// JS context routes through gw.JSValAttr. Both are handled in the value-emit
// section below by their respective branches.
func emitExprAttr(b *bytes.Buffer, a *ast.ExprAttr, resolved map[ast.Node]types.Type, table filterTable, imports map[string]bool, cls *attrclass.Classifier, bag *diag.Bag) bool {
	// (1) whole-attr `?` try-marker is deferred (per-stage `?` is caught by lowerPipe).
	if a.Try {
		bag.Errorf(a.Pos(), a.End(), "unsupported-try", "`?` try-marker in attribute %q not supported yet", a.Name)
		return false
	}
	// (2) value expression: lower a pipeline to nested std calls (same lowerPipe
	// the probe used, so resolved[a] is already the pipeline's RESULT type), else
	// the bare trimmed expr.
	expr := strings.TrimSpace(a.Expr)
	if len(a.Stages) > 0 {
		lowered, usedPkgs, err := lowerPipe(a.Expr, a.Stages, table)
		if err != nil {
			bag.Errorf(a.Pos(), a.End(), "unresolved-pipeline", "%s", strings.TrimPrefix(err.Error(), "codegen: "))
			return false
		}
		for _, path := range usedPkgs {
			imports[path] = true
		}
		expr = lowered
	}

	t, ok := resolved[a]
	if !ok || t == nil {
		bag.Errorf(a.Pos(), a.End(), "unresolved-attr", "could not resolve type of attribute %q value %q", a.Name, a.Expr)
		return false
	}

	// A bool-typed value is a boolean attribute regardless of context — EXCEPT in
	// a JS context, where a bool must JSON-encode to "true"/"false" inside the
	// attribute value (e.g. Alpine x-show={ b } → x-show="true"), not become a
	// bare boolean attribute.
	if classify(t) == catBool && cls.Context(a.Name) != attrclass.CtxJS {
		fmt.Fprintf(b, "\t\t_gsxgw.BoolAttr(%s, bool(%s))\n", strconv.Quote(a.Name), expr)
		return true
	}

	fmt.Fprintf(b, "\t\t_gsxgw.S(%s)\n", strconv.Quote(" "+a.Name+`="`))
	if cls.Context(a.Name) == attrclass.CtxJS {
		// JS-context attribute, whole-value form (x-data={ expr }): JSON-encode the
		// value then HTML-attr-escape. JSValAttr accepts any type (numbers, structs,
		// maps, bools) and passes gsx.RawJS through. No type-classification needed,
		// same as a JSCtxValue hole.
		fmt.Fprintf(b, "\t\t_gsxgw.JSValAttr(%s)\n", expr)
	} else if cls.Context(a.Name) == attrclass.CtxURL && !isRawURL(t) {
		// URL context: value must be string-like; sanitize + escape. A gsx.RawURL
		// value (isRawURL) is the author's vouch — fall through to gw.AttrValue,
		// which entity-escapes but skips the scheme allow-list.
		fmt.Fprintf(b, "\t\t_gsxgw.URL(%s)\n", urlStringExpr(expr, t))
	} else if cls.Context(a.Name) == attrclass.CtxCSS {
		// CSS context (the built-in `style` parses to a composable ClassAttr, so this
		// branch is reached by a user CSS-rule attribute in whole-value ={ } form).
		// Mirror the <style>-block emission: a gsx.RawCSS value is the author's
		// opt-out (emitted raw via gw.S), strings/Stringers go through the gw.CSS
		// value-filter, numbers are formatted raw, any other type is an error.
		if !emitRenderCSS(b, expr, t, imports, a, bag) {
			return false
		}
	} else {
		if !emitAttrValue(b, expr, t, imports, a, bag) {
			return false
		}
	}
	fmt.Fprintf(b, "\t\t_gsxgw.S(%s)\n", strconv.Quote(`"`))
	return true
}

// isRawURL reports whether t is the gsx.RawURL named type — the author's opt-out
// from URL scheme sanitizing. Such a value is routed through gw.AttrValue
// (entity-escaped, scheme unchecked) instead of gw.URL.
func isRawURL(t types.Type) bool {
	n, ok := types.Unalias(t).(*types.Named)
	if !ok {
		return false
	}
	obj := n.Obj()
	return obj != nil && obj.Name() == "RawURL" &&
		obj.Pkg() != nil && obj.Pkg().Path() == "github.com/gsxhq/gsx"
}

// urlStringExpr renders a URL-context value as a string expression for gw.URL.
func urlStringExpr(expr string, t types.Type) string {
	if classify(t) == catString {
		return "string(" + expr + ")"
	}
	return expr // non-string URL values are unusual; let the Go compiler check gw.URL's arg
}

// emitAttrValue writes a non-URL attribute value via gw.AttrValue, §5 type-aware.
// n is the AST node for positioning any error diagnostic.
func emitAttrValue(b *bytes.Buffer, expr string, t types.Type, imports map[string]bool, n ast.Node, bag *diag.Bag) bool {
	switch classify(t) {
	case catString:
		fmt.Fprintf(b, "\t\t_gsxgw.AttrValue(string(%s))\n", expr)
	case catBytes:
		fmt.Fprintf(b, "\t\t_gsxgw.AttrValue(string(%s))\n", expr)
	case catInt:
		imports["strconv"] = true
		fmt.Fprintf(b, "\t\t_gsxgw.AttrValue(strconv.FormatInt(int64(%s), 10))\n", expr)
	case catUint:
		imports["strconv"] = true
		fmt.Fprintf(b, "\t\t_gsxgw.AttrValue(strconv.FormatUint(uint64(%s), 10))\n", expr)
	case catFloat:
		imports["strconv"] = true
		fmt.Fprintf(b, "\t\t_gsxgw.AttrValue(strconv.FormatFloat(float64(%s), 'g', -1, 64))\n", expr)
	case catStringer:
		fmt.Fprintf(b, "\t\t_gsxgw.AttrValue((%s).String())\n", expr)
	default:
		bag.Errorf(n.Pos(), n.End(), "unsupported-attr-type", "attribute value type %s not supported (string/number/bool/Stringer only)", t)
		return false
	}
	return true
}

// isComponentTag reports whether a tag names a component (uppercase first letter
// or dotted, e.g. ui.Button) rather than an HTML element.
func isComponentTag(tag string) bool {
	if tag == "" {
		return false
	}
	if strings.Contains(tag, ".") {
		return true
	}
	return tag[0] >= 'A' && tag[0] <= 'Z'
}

// singleRoot reports the component body's single root element when the body has
// EXACTLY one meaningful top-level node and that node is a NON-component
// `*ast.Element`. Pure-whitespace `*ast.Text` (Value is all spaces/newlines) and
// HTML comments are insignificant and skipped; any other node kind alongside (or
// as) the candidate — a Doctype, a fragment, multiple elements, a control-flow
// node, an interp, or a component-tag element — yields (nil, false). It drives
// child auto-fallthrough eligibility: only a single HTML-element root can receive
// the synthesized Attrs bag (class-merge + spread at that element).
func singleRoot(body []ast.Markup) (*ast.Element, bool) {
	var root *ast.Element
	for _, n := range body {
		switch t := n.(type) {
		case *ast.Text:
			if strings.TrimSpace(t.Value) == "" {
				continue // insignificant whitespace
			}
			return nil, false // non-whitespace text alongside → not single-root
		case *ast.HTMLComment:
			continue // comments are insignificant
		case *ast.Element:
			if root != nil || isComponentTag(t.Tag) {
				return nil, false // a second element, or a component-tag root
			}
			root = t
		default:
			return nil, false // fragment / control-flow / interp / doctype → not single-root
		}
	}
	if root == nil {
		return nil, false
	}
	// The root is fallthrough-eligible only when ALL its own attributes have
	// STATICALLY-KNOWN names: caller-wins emit guards each root attr with
	// `if !_gsxp.Attrs.Has(name)` and merges the bag's class/style — both need the
	// static name. A *CondAttr (`{ if … { id=… } }`) or *SpreadAttr (`<div {...x}>`) sets attrs
	// whose names/values are only known at runtime, so neither the drop set nor the
	// class merge can account for them — a colliding fallthrough would emit a
	// duplicate attribute (and bypass class-merge). Such a root is NOT auto-eligible;
	// a fallthrough onto it then fails closed (no Attrs field → Go unknown-field).
	for _, a := range root.Attrs {
		switch a.(type) {
		case *ast.CondAttr, *ast.SpreadAttr:
			return nil, false
		}
	}
	return root, true
}

// usesChildren reports whether any interpolation in the markup body is a bare
// `{children}` reference. It mirrors the markup walks (recursing control flow,
// non-component element children, and fragments); a child component's OWN attrs
// are props (not slot content), and a child component's children render in THIS
// parent scope, so those are recursed too — a `{children}` inside a nested
// element or another component's slot still counts. The result drives whether the
// component synthesizes a `Children gsx.Node` field + `children` local binding.
func usesChildren(body []ast.Markup) bool {
	for _, n := range body {
		switch t := n.(type) {
		case *ast.Interp:
			if strings.TrimSpace(t.Expr) == "children" {
				return true
			}
		case *ast.Element:
			// Recurse children for BOTH plain elements and child components: a
			// component's slot content renders in this scope, so a `{children}` there
			// references THIS component's slot. (We do not walk a component's attrs —
			// those are props.)
			if usesChildren(t.Children) {
				return true
			}
		case *ast.Fragment:
			if usesChildren(t.Children) {
				return true
			}
		case *ast.ForMarkup:
			if usesChildren(t.Body) {
				return true
			}
		case *ast.IfMarkup:
			if usesChildren(t.Then) || usesChildren(t.Else) {
				return true
			}
		case *ast.SwitchMarkup:
			for _, cc := range t.Cases {
				if usesChildren(cc.Body) {
					return true
				}
			}
		}
	}
	return false
}

// usesAttrs reports whether the markup body references the EXACT identifier
// `attrs` in any value-position Go fragment — the MANUAL-mode trigger. It mirrors
// usesChildren's recursion (control flow, fragments, non-component and component
// element children incl. named-slot values) but detects via valueIdents, which is
// token-based: it matches the bare ident `attrs` (e.g. `{...attrs}` SpreadAttr,
// `{...attrs.Without("id")}`, `{ attrs.Class() }` interp, an `attrs`-referencing
// control-flow clause), and crucially does NOT match a longer ident like
// `attrsList` (a different token) nor a selector field after a `.` (e.g.
// `x.attrs`). A component's SIMPLE attrs (props) are NOT walked — those are the
// caller's prop exprs, not this component's body — but its named-slot values and
// slot children render in THIS scope and CAN reference this component's `attrs`,
// so they are recursed.
func usesAttrs(body []ast.Markup) bool {
	refsAttrs := func(src string) bool { return valueIdents(src)["attrs"] }
	for _, n := range body {
		switch t := n.(type) {
		case *ast.Interp:
			if refsAttrs(t.Expr) {
				return true
			}
			for _, st := range t.Stages {
				if st.Args != "" && refsAttrs(st.Args) {
					return true
				}
			}
		case *ast.Element:
			// A non-component element: walk its attrs (spread/expr/class/cond) for an
			// `attrs` reference. A component element: skip its SIMPLE attrs (props) but
			// recurse named-slot values, which render in this scope. Both recurse
			// children.
			if !isComponentTag(t.Tag) {
				if attrsRefAttrs(t.Attrs) {
					return true
				}
			} else {
				found := false
				walkMarkupAttrs(t.Attrs, func(value []ast.Markup) {
					if usesAttrs(value) {
						found = true
					}
				})
				if found {
					return true
				}
			}
			if usesAttrs(t.Children) {
				return true
			}
		case *ast.Fragment:
			if usesAttrs(t.Children) {
				return true
			}
		case *ast.ForMarkup:
			if refsAttrs(t.Clause) || usesAttrs(t.Body) {
				return true
			}
		case *ast.IfMarkup:
			if refsAttrs(t.Cond) || usesAttrs(t.Then) || usesAttrs(t.Else) {
				return true
			}
		case *ast.SwitchMarkup:
			if refsAttrs(t.Tag) {
				return true
			}
			for _, cc := range t.Cases {
				if refsAttrs(cc.List) || usesAttrs(cc.Body) {
					return true
				}
			}
		case *ast.GoBlock:
			if refsAttrs(t.Code) {
				return true
			}
		}
	}
	return false
}

// attrsRefAttrs reports whether any verbatim-emitted Go fragment in a (non-
// component) element's attr list references the identifier `attrs`: a
// `{...attrs}` SpreadAttr's Expr, a composable-class part Expr/Cond, an ExprAttr
// Expr or its pipeline args, or — recursing — a CondAttr's Cond and branches.
// These are exactly the fragments collectAttrSrc feeds to the ident walks, so a
// manual `attrs` reference anywhere in them is detected.
func attrsRefAttrs(attrs []ast.Attr) bool {
	refsAttrs := func(src string) bool { return valueIdents(src)["attrs"] }
	for _, a := range attrs {
		switch at := a.(type) {
		case *ast.SpreadAttr:
			if refsAttrs(at.Expr) {
				return true
			}
		case *ast.ClassAttr:
			for _, p := range at.Parts {
				if refsAttrs(p.Expr) || (p.Cond != "" && refsAttrs(p.Cond)) {
					return true
				}
			}
		case *ast.ExprAttr:
			if refsAttrs(at.Expr) {
				return true
			}
			for _, st := range at.Stages {
				if st.Args != "" && refsAttrs(st.Args) {
					return true
				}
			}
		case *ast.CondAttr:
			if refsAttrs(at.Cond) || attrsRefAttrs(at.Then) || attrsRefAttrs(at.Else) {
				return true
			}
		case *ast.JSAttr:
			// A JS-attribute value's @{ } interps render in this scope, so an `attrs`
			// reference there needs the local bound.
			if usesAttrs(at.Segments) {
				return true
			}
		}
	}
	return false
}

// childInvocation resolves a child-component tag to its CALL shape, applying the
// method-vs-package disambiguation. It is the SINGLE source of the call target +
// props-type name shared by genChildComponent (emit) and emitProbes (probe), so
// the two never drift on which call/props-struct a `<X.Y/>` invokes.
//
// Disambiguation (syntactic, deterministic): split el.Tag on the first `.` into
// (left, method). If the enclosing component is a method component (recvVar != "")
// AND left == recvVar → METHOD invocation: callTarget = `<recvVar>.<method>`,
// propsType = `<recvTypeName><method>Props`. Otherwise → existing PACKAGE-function
// path: callTarget = el.Tag, propsType = el.Tag + "Props" (e.g. `ui.AppShell` and
// `ui.AppShellProps`, or a same-file uppercase `Card` / `CardProps`).
//
// A NULLARY method invocation — a method whose call has NO props struct — happens
// only when isMethod AND the element has no attrs AND no children (a method that
// places `{children}` has a Children field, so children imply a props literal).
// The caller decides nullary via isNullaryCall below; this helper only reports
// the disambiguation result.
func childInvocation(el *ast.Element, recvVar, recvTypeName string) (callTarget, propsType string, isMethod bool) {
	if recvVar != "" {
		if i := strings.IndexByte(el.Tag, '.'); i >= 0 {
			left, method := el.Tag[:i], el.Tag[i+1:]
			if left == recvVar {
				return recvVar + "." + method, recvTypeName + method + "Props", true
			}
		}
	}
	return el.Tag, el.Tag + "Props", false
}

// genChildComponent lowers a child-component element to a gw.Node render call,
// building the props struct literal from the element's attributes. When the
// element has children, the slot markup is passed as a `Children gsx.Node`
// field — a gsx.Func render closure mirroring genComponent's, so the slot renders
// in THIS (parent) scope, where its interps' params/loop vars are bound.
//
// recvVar/recvTypeName are the ENCLOSING component's receiver var + type name
// (empty for a function component); they drive the method-vs-package
// disambiguation via childInvocation.
func genChildComponent(b *bytes.Buffer, el *ast.Element, resolved map[ast.Node]types.Type, table filterTable, structFields, nodeProps map[string]map[string]bool, imports map[string]bool, fset *token.FileSet, recvVar, recvTypeName string, cls *attrclass.Classifier, bag *diag.Bag) bool {
	callTarget, propsType, isMethod := childInvocation(el, recvVar, recvTypeName)
	// A nullary METHOD invocation — no attrs, no children — has no props struct, so
	// it is called bare: `p.Content()`. Any attrs or children mean the method has a
	// props struct (children → a Children field), so we build a props literal.
	isNullaryCall := isMethod && len(el.Attrs) == 0 && len(el.Children) == 0
	if isNullaryCall {
		fmt.Fprintf(b, "\t\t_gsxgw.Node(ctx, %s())\n", callTarget)
		return true
	}

	// Build the FULL props literal (simple attr fields + markup-attr slot fields +
	// Children) through the shared childPropsLiteral. The slot VALUE for both
	// markup attributes and the {children} slot is a real gsx.Func render closure
	// (emitSlotClosure), rendered in THIS (parent) scope so its interps' params/
	// loop vars are bound. emitProbes drives the same builder with a typed-nil
	// slotValue, so emit and probe agree on WHICH fields exist — only the VALUE
	// differs, and they cannot drift.
	fields, err := childPropsLiteral(el, propsType, "gsx", structFields, nodeProps[propsType], func(nodes []ast.Markup) (string, error) {
		s, ok := emitSlotClosure(nodes, resolved, table, structFields, nodeProps, imports, fset, recvVar, recvTypeName, cls, bag)
		if !ok {
			return "", fmt.Errorf("slot closure failed")
		}
		return s, nil
	})
	if err != nil {
		// Convert the childPropsLiteral error to a positioned diagnostic.
		// An attrError carries the specific attr's position; fall back to the element.
		var ae *attrError
		if errors.As(err, &ae) {
			bag.Errorf(ae.pos, ae.end, ae.code, "%s", ae.msg)
		} else {
			bag.Errorf(el.Pos(), el.End(), childPropsErrorCode(err), "%s", strings.TrimPrefix(err.Error(), "codegen: "))
		}
		return false
	}
	fmt.Fprintf(b, "\t\t_gsxgw.Node(ctx, %s(%s{%s}))\n", callTarget, propsType, fields)
	return true
}

// attrError is an error from childPropsLiteral that carries the offending attr
// node's position so callers can emit a positioned diagnostic. The msg field has
// the "codegen: " prefix stripped; code is already resolved via childPropsErrorCode.
type attrError struct {
	pos  token.Pos
	end  token.Pos
	code string
	msg  string
}

func (e *attrError) Error() string { return e.msg }

// childPropsErrorCode returns the diagnostic error code for a childPropsLiteral
// error, based on the error message content.
func childPropsErrorCode(err error) string {
	msg := err.Error()
	switch {
	case strings.Contains(msg, "class attribute"):
		return "unsupported-component-attr"
	case strings.Contains(msg, "spread attribute"):
		return "unsupported-component-attr"
	case strings.Contains(msg, "conditional attribute"):
		return "unsupported-component-attr"
	case strings.Contains(msg, "pipeline/`?`"):
		return "unsupported-child-pipeline"
	case strings.Contains(msg, "non-identifier attribute"):
		return "unsupported-attr-name"
	case strings.Contains(msg, "unknown attribute"):
		return "unsupported-attr"
	case strings.Contains(msg, "slot closure"):
		return "unsupported-node"
	default:
		return "unsupported-component-attr"
	}
}

// emitSlotClosure renders a slot (the {children} markup or a named markup-attr
// value) as a gsx.Func render closure string. The closure mirrors genComponent
// EXACTLY — same reserved idents (_gsxw/_gsxgw), gsx.W/gsx.Func, and trailing
// Err() — so the slot streams to the same output, in THIS (parent) scope. It is
// shared by the Children slot and every named markup slot so they cannot drift.
func emitSlotClosure(nodes []ast.Markup, resolved map[ast.Node]types.Type, table filterTable, structFields, nodeProps map[string]map[string]bool, imports map[string]bool, fset *token.FileSet, recvVar, recvTypeName string, cls *attrclass.Classifier, bag *diag.Bag) (string, bool) {
	var slot bytes.Buffer
	slot.WriteString("gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {\n")
	slot.WriteString("\t\t_gsxgw := gsx.W(_gsxw)\n")
	for _, c := range nodes {
		if !genNode(&slot, c, resolved, table, structFields, nodeProps, imports, fset, recvVar, recvTypeName, cls, bag) {
			return "", false
		}
	}
	slot.WriteString("\t\treturn _gsxgw.Err()\n")
	slot.WriteString("\t})")
	return slot.String(), true
}

// childPropsLiteral builds the comma-joined field list for a child component's
// props struct literal (e.g. `Title: "Hi", Featured: true, Header: <slot>`) from
// the element's attributes and children. It is the SINGLE source of the props
// literal so the render emission (genChildComponent) and the type-check probe
// (emitProbes) cannot drift — they pass the SAME field set, differing only in the
// slot VALUE supplied by slotValue (a real gsx.Func closure for emission, a
// typed-nil for the probe).
//
// It SPLITS each Static/Expr/Bool attr via isPropField(propFields[propsType], …):
//   - a DECLARED prop name → a props-struct field (static→quoted, expr→trimmed
//     expr rejecting Try/Stages, bool→true), exactly as before; and
//   - anything else (a non-identifier name like `data-test`/`@click`/`hx-*`, or an
//     undeclared identifier on a known same-package child) → a FALLTHROUGH bag
//     entry keyed by the attr's RAW name (static→quoted value, bool→true, expr→
//     trimmed expr).
//
// A markup attribute is always a named slot (rendered via slotValue); composed
// class/spread/conditional attrs on a component still error. When ≥1 fallthrough
// entry exists, a single `Attrs: gsx.Attrs{…}` field is appended (after Children);
// with none, NO Attrs field is emitted (so a pure-props invocation is unchanged).
// rtPkg is the package qualifier for the gsx runtime (`gsx` in emitted code,
// `_gsxrt` in a type-check skeleton), used only to name the fallthrough-bag type
// `<rtPkg>.Attrs` so emit and probe reference the SAME runtime type under their
// respective aliases.
// nodeFields is the child props type's set of declared gsx.Node fields
// (nodeProps[propsType]); a non-node value bound to one of these is promoted via
// rtPkg.Val/rtPkg.Text so a renderable value fills a gsx.Node prop.
func childPropsLiteral(el *ast.Element, propsType, rtPkg string, propFields map[string]map[string]bool, nodeFields map[string]bool, slotValue func(nodes []ast.Markup) (string, error)) (string, error) {
	declared := propFields[propsType] // nil for cross-package / unknown → graceful
	var fields []string
	var bag []string // fallthrough entries: `"<rawName>": <value>`
	for _, a := range el.Attrs {
		switch t := a.(type) {
		case *ast.StaticAttr:
			if isPropField(declared, t.Name) {
				if err := checkComponentAttrName(t.Name, el.Tag); err != nil {
					return "", err
				}
				if nodeFields[fieldName(t.Name)] {
					fields = append(fields, fmt.Sprintf("%s: %s.Text(%s)", fieldName(t.Name), rtPkg, strconv.Quote(t.Value)))
				} else {
					fields = append(fields, fmt.Sprintf("%s: %s", fieldName(t.Name), strconv.Quote(t.Value)))
				}
			} else {
				bag = append(bag, fmt.Sprintf("%s: %s", strconv.Quote(t.Name), strconv.Quote(t.Value)))
			}
		case *ast.ExprAttr:
			if isPropField(declared, t.Name) {
				if err := checkComponentAttrName(t.Name, el.Tag); err != nil {
					return "", err
				}
				if t.Try || len(t.Stages) > 0 {
					msg := fmt.Sprintf("pipeline/`?` on child-component prop %q (<%s>) not supported yet", t.Name, el.Tag)
					return "", &attrError{pos: t.Pos(), end: t.End(), code: "unsupported-child-pipeline", msg: msg}
				}
				if nodeFields[fieldName(t.Name)] {
					fields = append(fields, fmt.Sprintf("%s: %s.Val(%s)", fieldName(t.Name), rtPkg, strings.TrimSpace(t.Expr)))
				} else {
					fields = append(fields, fmt.Sprintf("%s: %s", fieldName(t.Name), strings.TrimSpace(t.Expr)))
				}
			} else {
				if t.Try || len(t.Stages) > 0 {
					msg := fmt.Sprintf("pipeline/`?` on child-component fallthrough attr %q (<%s>) not supported yet", t.Name, el.Tag)
					return "", &attrError{pos: t.Pos(), end: t.End(), code: "unsupported-child-pipeline", msg: msg}
				}
				bag = append(bag, fmt.Sprintf("%s: %s", strconv.Quote(t.Name), strings.TrimSpace(t.Expr)))
			}
		case *ast.BoolAttr:
			if isPropField(declared, t.Name) {
				if err := checkComponentAttrName(t.Name, el.Tag); err != nil {
					return "", err
				}
				if nodeFields[fieldName(t.Name)] {
					fields = append(fields, fmt.Sprintf("%s: %s.Val(true)", fieldName(t.Name), rtPkg))
				} else {
					fields = append(fields, fmt.Sprintf("%s: true", fieldName(t.Name)))
				}
			} else {
				bag = append(bag, fmt.Sprintf("%s: true", strconv.Quote(t.Name)))
			}
		case *ast.MarkupAttr:
			// A markup attribute (`header={ <h1/> }`) is a NAMED slot bound to a
			// declared `gsx.Node` prop. Its name must be a valid field identifier; its
			// VALUE is rendered by slotValue (a gsx.Func closure on emit, a typed-nil
			// on probe) — the SAME machinery as the {children} slot. A named slot is
			// never a fallthrough attr.
			if err := checkComponentAttrName(t.Name, el.Tag); err != nil {
				return "", err
			}
			val, err := slotValue(t.Value)
			if err != nil {
				return "", err
			}
			fields = append(fields, fmt.Sprintf("%s: %s", fieldName(t.Name), val))
		case *ast.ClassAttr:
			msg := fmt.Sprintf("class attribute on a component (<%s>) not supported yet", el.Tag)
			return "", &attrError{pos: t.Pos(), end: t.End(), code: "unsupported-component-attr", msg: msg}
		case *ast.SpreadAttr:
			msg := fmt.Sprintf("spread attribute on a component (<%s>) not supported yet", el.Tag)
			return "", &attrError{pos: t.Pos(), end: t.End(), code: "unsupported-component-attr", msg: msg}
		case *ast.CondAttr:
			msg := fmt.Sprintf("conditional attribute on a component (<%s>) not supported yet", el.Tag)
			return "", &attrError{pos: t.Pos(), end: t.End(), code: "unsupported-component-attr", msg: msg}
		default:
			msg := fmt.Sprintf("unknown attribute %T on component (<%s>)", a, el.Tag)
			return "", &attrError{pos: a.Pos(), end: a.End(), code: "unsupported-component-attr", msg: msg}
		}
	}
	if len(el.Children) > 0 {
		val, err := slotValue(el.Children)
		if err != nil {
			return "", err
		}
		fields = append(fields, "Children: "+val)
	}
	if len(bag) > 0 {
		fields = append(fields, fmt.Sprintf("Attrs: %s.Attrs{%s}", rtPkg, strings.Join(bag, ", ")))
	}
	return strings.Join(fields, ", "), nil
}

// isPropField reports whether a child-invocation attribute named `name` maps to a
// DECLARED props-struct field (→ a struct field) versus a FALLTHROUGH attr (→ the
// Attrs bag). declared is the child's prop-field set (nil for a cross-package or
// otherwise unknown child).
//
//   - A non-identifier name (data-test, @click, hx-*) can never be a Go field → it
//     falls through.
//   - The synthesized Attrs/Children fields are never caller-set props → fall
//     through (Children is supplied as slot markup, never a simple attr).
//   - When declared is nil (cross-package / unknown), assume an identifier attr IS
//     a prop — today's behavior. This means a cross-package child's NON-identifier
//     fallthrough WORKS (the common data-*/@/hx-* case), but a cross-package
//     UNDECLARED-IDENTIFIER attr is wrongly assumed a prop and surfaces at the
//     final `go build` of the .x.go. A future cross-package enhancement can resolve
//     imported struct fields; this task does not.
//   - Otherwise, membership in declared decides.
func isPropField(declared map[string]bool, name string) bool {
	if !token.IsIdentifier(name) {
		return false
	}
	fn := fieldName(name)
	if fn == "Attrs" || fn == "Children" {
		return false
	}
	if declared == nil {
		return true
	}
	return declared[fn]
}

// checkComponentAttrName rejects a prop attribute name that is not a Go identifier.
// It is now only reached on the isPropField (declared-prop) branch — a
// non-identifier name is classified as a fallthrough attr by isPropField and never
// reaches here, so this guards only a malformed declared-prop name.
func checkComponentAttrName(name, tag string) error {
	if !token.IsIdentifier(name) {
		return fmt.Errorf("codegen: non-identifier attribute %q on component %s (attribute fallthrough not supported yet)", name, tag)
	}
	return nil
}
