package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"sort"
	"strconv"
	"strings"

	"github.com/gsxhq/gsx/ast"
)

// generateFile emits the .x.go for a parsed gsx file given already-resolved
// interpolation types.
func generateFile(file *ast.File, resolved map[*ast.Interp]types.Type) ([]byte, error) {
	imports := map[string]bool{
		"context":              true,
		"io":                   true,
		"github.com/gsxhq/gsx": true,
	}
	// Import GoChunks are folded into the import region (they must precede all
	// other declarations); everything else flows into the body. Aliased / dot /
	// blank imports are kept verbatim; plain imports merge into the import set so
	// they dedupe against the runtime imports the generator already needs.
	var aliased []importSpec
	var body bytes.Buffer
	for _, d := range file.Decls {
		switch v := d.(type) {
		case *ast.GoChunk:
			if specs := importSpecsOf(v.Src); specs != nil {
				for _, s := range specs {
					if s.name == "" {
						imports[s.path] = true
					} else {
						aliased = append(aliased, s)
					}
				}
			} else {
				body.WriteString(strings.TrimSpace(v.Src))
				body.WriteString("\n\n")
			}
		case *ast.Component:
			if err := genComponent(&body, v, resolved, imports); err != nil {
				return nil, err
			}
		}
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by gsx; DO NOT EDIT.\n\npackage %s\n\n", file.Package)
	writeImports(&b, imports, aliased)
	b.Write(body.Bytes())
	return format.Source(b.Bytes())
}

func writeImports(b *bytes.Buffer, imports map[string]bool, aliased []importSpec) {
	var std, ext []string
	for imp := range imports {
		if strings.Contains(imp, ".") {
			ext = append(ext, imp)
		} else {
			std = append(std, imp)
		}
	}
	sort.Strings(std)
	sort.Strings(ext)
	sort.Slice(aliased, func(i, j int) bool { return aliased[i].path < aliased[j].path })
	b.WriteString("import (\n")
	for _, imp := range std {
		fmt.Fprintf(b, "\t%q\n", imp)
	}
	if len(std) > 0 && (len(ext) > 0 || len(aliased) > 0) {
		b.WriteString("\n")
	}
	for _, imp := range ext {
		fmt.Fprintf(b, "\t%q\n", imp)
	}
	for _, imp := range aliased {
		fmt.Fprintf(b, "\t%s %q\n", imp.name, imp.path)
	}
	b.WriteString(")\n\n")
}

func genComponent(b *bytes.Buffer, c *ast.Component, resolved map[*ast.Interp]types.Type, imports map[string]bool) error {
	if c.Recv != "" {
		return fmt.Errorf("codegen spike: method components not supported yet (%s)", c.Name)
	}
	params, err := parseParams(c.Params)
	if err != nil {
		return err
	}

	// Props struct (field types are syntactic — straight from the param list).
	fmt.Fprintf(b, "type %sProps struct {\n", c.Name)
	for _, p := range params {
		fmt.Fprintf(b, "\t%s %s\n", fieldName(p.name), p.typ)
	}
	fmt.Fprintf(b, "}\n\n")

	// Render func. Bind each USED param to a same-named local so interpolation
	// expressions can be emitted verbatim.
	fmt.Fprintf(b, "func %s(p %sProps) gsx.Node {\n", c.Name, c.Name)
	b.WriteString("\treturn gsx.Func(func(ctx context.Context, w io.Writer) error {\n")
	used := usedParams(c, params)
	for _, p := range params {
		if used[p.name] {
			fmt.Fprintf(b, "\t\t%s := p.%s\n", p.name, fieldName(p.name))
		}
	}
	b.WriteString("\t\tgw := gsx.W(w)\n")
	for _, m := range c.Body {
		if err := genNode(b, m, resolved, imports); err != nil {
			return err
		}
	}
	b.WriteString("\t\treturn gw.Err()\n")
	b.WriteString("\t})\n}\n\n")
	return nil
}

func genNode(b *bytes.Buffer, n ast.Markup, resolved map[*ast.Interp]types.Type, imports map[string]bool) error {
	switch t := n.(type) {
	case *ast.Text:
		emitS(b, t.Value)
	case *ast.Element:
		if isComponentTag(t.Tag) {
			return genChildComponent(b, t)
		}
		if len(t.Attrs) > 0 {
			return fmt.Errorf("codegen spike: element attributes not supported yet (<%s>)", t.Tag)
		}
		if t.Void {
			emitS(b, "<"+t.Tag+"/>")
			return nil
		}
		emitS(b, "<"+t.Tag+">")
		for _, c := range t.Children {
			if err := genNode(b, c, resolved, imports); err != nil {
				return err
			}
		}
		emitS(b, "</"+t.Tag+">")
	case *ast.Interp:
		return genInterp(b, t, resolved, imports)
	default:
		return fmt.Errorf("codegen spike: unsupported markup node %T", n)
	}
	return nil
}

// genInterp emits the type-aware writer call for an interpolation. The type comes
// from the go/types resolution pass; the expression is emitted verbatim (params
// are in scope as locals).
func genInterp(b *bytes.Buffer, n *ast.Interp, resolved map[*ast.Interp]types.Type, imports map[string]bool) error {
	if n.Try {
		return fmt.Errorf("codegen spike: `?` try-marker not supported yet")
	}
	t, ok := resolved[n]
	if !ok || t == nil {
		return fmt.Errorf("codegen spike: could not resolve type of interpolation %q", n.Expr)
	}
	expr := strings.TrimSpace(n.Expr)
	switch classify(t) {
	case catString:
		fmt.Fprintf(b, "\t\tgw.Text(%s)\n", expr)
	case catBytes:
		fmt.Fprintf(b, "\t\tgw.Text(string(%s))\n", expr)
	case catInt:
		imports["strconv"] = true
		fmt.Fprintf(b, "\t\tgw.Text(strconv.FormatInt(int64(%s), 10))\n", expr)
	case catUint:
		imports["strconv"] = true
		fmt.Fprintf(b, "\t\tgw.Text(strconv.FormatUint(uint64(%s), 10))\n", expr)
	case catFloat:
		imports["strconv"] = true
		fmt.Fprintf(b, "\t\tgw.Text(strconv.FormatFloat(float64(%s), 'g', -1, 64))\n", expr)
	case catBool:
		imports["strconv"] = true
		fmt.Fprintf(b, "\t\tgw.Text(strconv.FormatBool(%s))\n", expr)
	case catStringer:
		fmt.Fprintf(b, "\t\tgw.Text((%s).String())\n", expr)
	case catNode:
		fmt.Fprintf(b, "\t\tgw.Node(ctx, %s)\n", expr)
	case catNodeSlice:
		fmt.Fprintf(b, "\t\tfor _, _gsxn := range %s {\n\t\t\tgw.Node(ctx, _gsxn)\n\t\t}\n", expr)
	default:
		return fmt.Errorf("codegen: interpolation %q has type %s; not a renderable type", expr, t)
	}
	return nil
}

func emitS(b *bytes.Buffer, s string) {
	fmt.Fprintf(b, "\t\tgw.S(%s)\n", strconv.Quote(s))
}

// isComponentTag reports whether a tag names a component (uppercase first letter
// or dotted, e.g. ui.Button) rather than an HTML element.
func isComponentTag(tag string) bool {
	if tag == "" {
		return false
	}
	if strings.Contains(tag, ".") {
		return true
	}
	return tag[0] >= 'A' && tag[0] <= 'Z'
}

// genChildComponent lowers a child-component element to a gw.Node render call.
// SPIKE: no props (attributes) or children on the child yet.
func genChildComponent(b *bytes.Buffer, el *ast.Element) error {
	if len(el.Attrs) > 0 {
		return fmt.Errorf("codegen spike: child-component props (attributes) not supported yet (<%s>)", el.Tag)
	}
	if len(el.Children) > 0 {
		return fmt.Errorf("codegen spike: child-component children not supported yet (<%s>)", el.Tag)
	}
	fmt.Fprintf(b, "\t\tgw.Node(ctx, %s(%sProps{}))\n", el.Tag, el.Tag)
	return nil
}
