package codegen

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/gsxhq/gsx/internal/diag"
	"github.com/gsxhq/gsx/internal/fullmin"
)

// TestGenerateDirsBasic verifies that GenerateDirs over setupChainModule's four
// package directories returns non-empty .gsx-keyed Files for each dir and that
// the components package (which imports util) resolves cross-package without any
// diagnostic errors (proving the util.Y reference type-checks cleanly).
func TestGenerateDirsBasic(t *testing.T) {
	t.Parallel()
	if testing.Short() {
		t.Skip("skipping module-resolution test in -short mode")
	}
	// setupChainModule returns a Module + root, but we want GenerateDirs so we
	// re-create the same temp structure manually via the helper's internals.
	// Since setupChainModule is package-internal, call it and extract root.
	_, root := setupChainModule(t)
	dirs := []string{
		filepath.Join(root, "util"),
		filepath.Join(root, "components"),
		filepath.Join(root, "pages"),
		filepath.Join(root, "solo"),
	}
	result, err := GenerateDirs(root, dirs, Options{FilterPkgs: []string{StdImportPath}}, nil)
	if err != nil {
		t.Fatalf("GenerateDirs: %v", err)
	}
	// Each dir must have at least one .gsx-keyed file with non-empty bytes.
	for _, dir := range dirs {
		dr, ok := result[dir]
		if !ok {
			t.Errorf("no result for dir %s", dir)
			continue
		}
		if len(dr.Files) == 0 {
			t.Errorf("dir %s: no generated files", dir)
		}
		for gsxPath, src := range dr.Files {
			if !strings.HasSuffix(gsxPath, ".gsx") {
				t.Errorf("dir %s: file key %q must end in .gsx", dir, gsxPath)
			}
			if len(src) == 0 {
				t.Errorf("dir %s: file %s has empty generated bytes", dir, gsxPath)
			}
		}
		// No error diagnostics: cross-package resolution (util.Y in components) must succeed.
		for _, d := range dr.Diags {
			if d.Severity == diag.Error {
				t.Errorf("dir %s: unexpected error diagnostic: %s", dir, d.Message)
			}
		}
	}
	// Specifically check components resolved the util.Y cross-package reference.
	compDir := filepath.Join(root, "components")
	compResult := result[compDir]
	if compResult.Files == nil {
		t.Fatal("components dir: no Files (cross-package resolution may have failed)")
	}
}

// TestGenerateDirsMinify verifies that CSSMinify options are threaded through
// GenerateDirs: a static <style> block with collapsible whitespace produces
// different output with CSSMinify:false vs CSSMinify:true.
func TestGenerateDirsMinify(t *testing.T) {
	t.Parallel()
	if testing.Short() {
		t.Skip("skipping module-resolution test in -short mode")
	}
	root := t.TempDir()
	repoRoot, _ := filepath.Abs("../..")
	writeFile(t, root, "go.mod",
		"module example.com/mintest2\n\ngo 1.26.1\n\nrequire github.com/gsxhq/gsx v0.0.0\n\nreplace github.com/gsxhq/gsx => "+repoRoot+"\n")
	pkgDir := filepath.Join(root, "views")
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		t.Fatal(err)
	}
	gsxPath := filepath.Join(pkgDir, "views.gsx")
	writeFile(t, pkgDir, "views.gsx",
		"package views\n\ncomponent Page() {\n\t<style>.a {  color : red ;  }</style>\n}\n")

	generate := func(opts Options) string {
		result, err := GenerateDirs(root, []string{pkgDir}, opts, nil)
		if err != nil {
			t.Fatalf("GenerateDirs: %v", err)
		}
		dr := result[pkgDir]
		b := dr.Files[gsxPath]
		if b == nil {
			t.Fatalf("no output for %s; files=%v", gsxPath, dr.Files)
		}
		return string(b)
	}

	noMin := generate(Options{FilterPkgs: []string{StdImportPath}, CSSMinify: false})
	builtinMin := generate(Options{FilterPkgs: []string{StdImportPath}, CSSMinify: true})
	fullMin := generate(Options{FilterPkgs: []string{StdImportPath}, CSSMinify: true, CSSMin: fullmin.CSS})

	// noMin: original CSS preserved verbatim. The open tag is split around the
	// auto-injected CSP nonce guard (_gsxgw.Nonce(ctx)), so the static string
	// literal starts after "<style" rather than "<style>".
	const wantNoMin = `_gsxgw.S(">.a {  color : red ;  }</style>")`
	if !strings.Contains(noMin, wantNoMin) {
		t.Errorf("noMin: expected verbatim CSS; got:\n%s", noMin)
	}
	// builtinMin: built-in safe whitespace pass.
	const wantBuiltin = `_gsxgw.S(">.a{color : red}</style>")`
	if !strings.Contains(builtinMin, wantBuiltin) {
		t.Errorf("builtinMin: expected safe-minified CSS; got:\n%s", builtinMin)
	}
	// fullMin: aggressive tdewolff pass.
	const wantFull = `_gsxgw.S(">.a{color:red}</style>")`
	if !strings.Contains(fullMin, wantFull) {
		t.Errorf("fullMin: expected aggressively-minified CSS; got:\n%s", fullMin)
	}
	const wantOpenTag = `_gsxgw.S("<style")` + "\n\t\t_gsxgw.Nonce(ctx)\n"
	for name, got := range map[string]string{"noMin": noMin, "builtinMin": builtinMin, "fullMin": fullMin} {
		if !strings.Contains(got, wantOpenTag) {
			t.Errorf("%s: expected split open tag with nonce guard; got:\n%s", name, got)
		}
	}
	// All three must differ.
	if noMin == builtinMin {
		t.Error("noMin and builtinMin are identical (CSSMinify not threaded?)")
	}
	if builtinMin == fullMin {
		t.Error("builtinMin and fullMin are identical (CSSMin func not threaded?)")
	}
}
