package codegen

import (
	"os"
	"os/exec"
	"slices"
	"strings"
	"testing"

	"github.com/gsxhq/gsx/internal/codegen/stdpath"
)

// TestStdlibIndexHasExpectedPackages is an always-on guard that the table is
// present, plausible, and still shaped the way the resolver depends on. It
// shells out to nothing, so unlike TestStdlibIndexIsFresh it cannot drift with
// the host toolchain.
//
// The ambiguous entries are the load-bearing ones: ResolveImportCandidates only
// consults a package's exported symbols when a NAME maps to more than one path.
// If `rand` or `template` ever collapsed to a single path, the disambiguation
// branch would silently stop being exercised and `rand.IntN` could start
// resolving to `math/rand`.
func TestStdlibIndexHasExpectedPackages(t *testing.T) {
	if n := len(stdlibIndex); n < 150 {
		t.Fatalf("stdlibIndex has only %d names — the table looks truncated or unbuilt", n)
	}
	for name, want := range map[string][]string{
		"fmt":      {"fmt"},
		"strings":  {"strings"},
		"context":  {"context"},
		"io":       {"io"},
		"rand":     {"crypto/rand", "math/rand", "math/rand/v2"},
		"template": {"html/template", "text/template"},
	} {
		got, ok := stdlibIndex[name]
		if !ok {
			t.Errorf("stdlibIndex missing %q — run `go generate ./internal/codegen`", name)
			continue
		}
		if !slices.Equal(got, want) {
			t.Errorf("stdlibIndex[%q] = %v, want %v — run `go generate ./internal/codegen`", name, got, want)
		}
	}
	if _, ok := stdlibIndex["internal"]; ok {
		t.Error(`stdlibIndex contains "internal": unimportable std packages leaked into the table`)
	}
}

// TestStdlibIndexIsFresh diffs the generated table against a live `go list std`.
// A Go upgrade that adds, removes, or renames a std package fails here rather
// than silently under-resolving. Regenerate with:
//
//	go generate ./internal/codegen
//
// Shares stdpath.Importable with the generator (mkstdlibindex/main.go) so this
// test cannot silently agree with a broken exclusion rule by re-implementing
// it inline — see TestStdlibIndexHasNoUnimportablePaths below for a check that
// does NOT share that implementation, and so actually exercises the rule.
//
// It is OPT-IN, not a CI gate. Run it after a Go upgrade, on the machine you
// regenerate the table from:
//
//	GSX_CHECK_STDLIB_INDEX=1 go test ./internal/codegen -run TestStdlibIndexIsFresh
//
// Why it cannot gate CI: comparing a committed artifact against a live
// `go list std` is environment-coupled by construction. `go list std` varies with
// the host toolchain even under an identical pinned GOOS/GOARCH/CGO_ENABLED —
// empirically, cross-listing GOOS=linux from darwin/arm64 yields 171 package
// names while native linux/amd64 yields 170 (`plugin` is listed in the former,
// not the latter). A pinned environment removes the cgo variance (`runtime/cgo`)
// but not this one. Making the check portable would mean either shipping a table
// that is the union over every supported platform, or asserting only a
// containment relation whose direction flips depending on which host generated
// the table — both worse than admitting this is a maintenance check.
//
// x/tools treats its own generated stdlib table the same way: regenerated by
// hand, not asserted against a live toolchain in CI.
//
// The always-on guards below carry the load instead:
// TestStdlibIndexHasNoUnimportablePaths (an independent property) and
// TestStdlibIndexHasExpectedPackages (the entries the resolver actually depends
// on). Neither shells out, so neither can drift with the host.
func TestStdlibIndexIsFresh(t *testing.T) {
	if os.Getenv("GSX_CHECK_STDLIB_INDEX") == "" {
		t.Skip("maintenance check; set GSX_CHECK_STDLIB_INDEX=1 after a Go upgrade (see doc comment)")
	}
	cmd := exec.Command("go", "list", "-f", "{{.Name}} {{.ImportPath}}", "std")
	cmd.Env = stdpath.GoListEnv()
	out, err := cmd.Output()
	if err != nil {
		t.Skipf("go list std: %v", err)
	}
	live := map[string][]string{}
	for line := range strings.SplitSeq(string(out), "\n") {
		f := strings.Fields(line)
		if len(f) != 2 || !stdpath.Importable(f[1]) {
			continue
		}
		live[f[0]] = append(live[f[0]], f[1])
	}
	if len(live) != len(stdlibIndex) {
		t.Fatalf("stdlibIndex has %d names, `go list std` has %d — run `go generate ./internal/codegen`", len(stdlibIndex), len(live))
	}
	for name, paths := range live {
		got, ok := stdlibIndex[name]
		if !ok {
			t.Errorf("stdlibIndex missing %q — run `go generate ./internal/codegen`", name)
			continue
		}
		if strings.Join(got, ",") != strings.Join(paths, ",") {
			t.Errorf("stdlibIndex[%q] = %v, want %v — run `go generate ./internal/codegen`", name, got, paths)
		}
	}
}

// TestStdlibIndexHasNoUnimportablePaths is an INDEPENDENT property check: it
// does not call stdpath.Importable (the shared helper both the generator and
// TestStdlibIndexIsFresh now use) or any other production code, so a bug
// shared by both of those call sites cannot hide from it. It walks every path
// actually baked into stdlibIndex and asserts, from scratch, that no
// `/`-separated component is exactly "internal" and no path starts with
// "vendor/" — Go's own visibility rule, re-derived here rather than trusted.
//
// This test FAILS against the table generated by the pre-fix substring filter
// (strings.Contains(path, "internal/")), which let encoding/json/internal,
// log/internal, log/slog/internal, and net/http/internal leak in under the
// name "internal" — none of those paths' LAST component was caught by a
// substring test for "internal/".
func TestStdlibIndexHasNoUnimportablePaths(t *testing.T) {
	for name, paths := range stdlibIndex {
		for _, p := range paths {
			for seg := range strings.SplitSeq(p, "/") {
				if seg == "internal" {
					t.Errorf("stdlibIndex[%q] contains %q, which has an `internal` path component and is not importable from user code", name, p)
				}
			}
			if strings.HasPrefix(p, "vendor/") {
				t.Errorf("stdlibIndex[%q] contains %q, which is a vendor path and not a real package", name, p)
			}
		}
	}
}
