package codegen

import (
	"os/exec"
	"strings"
	"testing"

	"github.com/gsxhq/gsx/internal/codegen/stdpath"
)

// TestStdlibIndexIsFresh diffs the generated table against a live `go list std`.
// A Go upgrade that adds, removes, or renames a std package fails here rather
// than silently under-resolving. Regenerate with:
//
//	go generate ./internal/codegen
//
// Shares stdpath.Importable with the generator (mkstdlibindex/main.go) so this
// test cannot silently agree with a broken exclusion rule by re-implementing
// it inline — see TestStdlibIndexHasNoUnimportablePaths below for a check that
// does NOT share that implementation, and so actually exercises the rule.
func TestStdlibIndexIsFresh(t *testing.T) {
	if testing.Short() {
		t.Skip("runs `go list std`")
	}
	out, err := exec.Command("go", "list", "-f", "{{.Name}} {{.ImportPath}}", "std").Output()
	if err != nil {
		t.Skipf("go list std: %v", err)
	}
	live := map[string][]string{}
	for line := range strings.SplitSeq(string(out), "\n") {
		f := strings.Fields(line)
		if len(f) != 2 || !stdpath.Importable(f[1]) {
			continue
		}
		live[f[0]] = append(live[f[0]], f[1])
	}
	if len(live) != len(stdlibIndex) {
		t.Fatalf("stdlibIndex has %d names, `go list std` has %d — run `go generate ./internal/codegen`", len(stdlibIndex), len(live))
	}
	for name, paths := range live {
		got, ok := stdlibIndex[name]
		if !ok {
			t.Errorf("stdlibIndex missing %q — run `go generate ./internal/codegen`", name)
			continue
		}
		if strings.Join(got, ",") != strings.Join(paths, ",") {
			t.Errorf("stdlibIndex[%q] = %v, want %v — run `go generate ./internal/codegen`", name, got, paths)
		}
	}
}

// TestStdlibIndexHasNoUnimportablePaths is an INDEPENDENT property check: it
// does not call stdpath.Importable (the shared helper both the generator and
// TestStdlibIndexIsFresh now use) or any other production code, so a bug
// shared by both of those call sites cannot hide from it. It walks every path
// actually baked into stdlibIndex and asserts, from scratch, that no
// `/`-separated component is exactly "internal" and no path starts with
// "vendor/" — Go's own visibility rule, re-derived here rather than trusted.
//
// This test FAILS against the table generated by the pre-fix substring filter
// (strings.Contains(path, "internal/")), which let encoding/json/internal,
// log/internal, log/slog/internal, and net/http/internal leak in under the
// name "internal" — none of those paths' LAST component was caught by a
// substring test for "internal/".
func TestStdlibIndexHasNoUnimportablePaths(t *testing.T) {
	for name, paths := range stdlibIndex {
		for _, p := range paths {
			for seg := range strings.SplitSeq(p, "/") {
				if seg == "internal" {
					t.Errorf("stdlibIndex[%q] contains %q, which has an `internal` path component and is not importable from user code", name, p)
				}
			}
			if strings.HasPrefix(p, "vendor/") {
				t.Errorf("stdlibIndex[%q] contains %q, which is a vendor path and not a real package", name, p)
			}
		}
	}
}
