// Code generated by 'yaegi extract github.com/gsxhq/gsx'. DO NOT EDIT.

package interp

import (
	"context"
	"github.com/gsxhq/gsx"
	"io"
	"reflect"
)

func init() {
	Symbols["github.com/gsxhq/gsx/gsx"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AttrsCond":   reflect.ValueOf(gsx.AttrsCond),
		"Class":       reflect.ValueOf(gsx.Class),
		"ClassIf":     reflect.ValueOf(gsx.ClassIf),
		"ClassMerger": reflect.ValueOf(&gsx.ClassMerger).Elem(),
		"ClassString": reflect.ValueOf(gsx.ClassString),
		"FilterCSS":   reflect.ValueOf(gsx.FilterCSS),
		"Fragment":    reflect.ValueOf(gsx.Fragment),
		"Raw":         reflect.ValueOf(gsx.Raw),
		"StyleString": reflect.ValueOf(gsx.StyleString),
		"StyleValue":  reflect.ValueOf(gsx.StyleValue),
		"Text":        reflect.ValueOf(gsx.Text),
		"Val":         reflect.ValueOf(gsx.Val),
		"W":           reflect.ValueOf(gsx.W),

		// type definitions
		"Attrs":     reflect.ValueOf((*gsx.Attrs)(nil)),
		"ClassPart": reflect.ValueOf((*gsx.ClassPart)(nil)),
		"Func":      reflect.ValueOf((*gsx.Func)(nil)),
		"Node":      reflect.ValueOf((*gsx.Node)(nil)),
		"RawCSS":    reflect.ValueOf((*gsx.RawCSS)(nil)),
		"RawJS":     reflect.ValueOf((*gsx.RawJS)(nil)),
		"RawURL":    reflect.ValueOf((*gsx.RawURL)(nil)),
		"Writer":    reflect.ValueOf((*gsx.Writer)(nil)),

		// interface wrapper definitions
		"_Node": reflect.ValueOf((*_github_com_gsxhq_gsx_Node)(nil)),
	}
}

// _github_com_gsxhq_gsx_Node is an interface wrapper for Node type
type _github_com_gsxhq_gsx_Node struct {
	IValue  interface{}
	WRender func(ctx context.Context, w io.Writer) error
}

func (W _github_com_gsxhq_gsx_Node) Render(ctx context.Context, w io.Writer) error {
	return W.WRender(ctx, w)
}
