// Code generated by 'yaegi extract github.com/gsxhq/gsx/std'. DO NOT EDIT.

package interp

import (
	"github.com/gsxhq/gsx/std"
	"reflect"
)

func init() {
	Symbols["github.com/gsxhq/gsx/std/std"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Default":  reflect.ValueOf(std.Default),
		"Format":   reflect.ValueOf(std.Format),
		"Join":     reflect.ValueOf(std.Join),
		"Lower":    reflect.ValueOf(std.Lower),
		"Pkg":      reflect.ValueOf(&std.Pkg).Elem(),
		"Trim":     reflect.ValueOf(std.Trim),
		"Truncate": reflect.ValueOf(std.Truncate),
		"Upper":    reflect.ValueOf(std.Upper),
	}
}
