// Code generated by gsx; DO NOT EDIT.

package views

import (
	"context"
	"io"

	"github.com/gsxhq/gsx"
	_gsxcm "github.com/gsxhq/gsx/examples/tailwind-merge/twcfg"
)

type CardProps struct {
	Children gsx.Node
	Attrs    gsx.Attrs
}

//line card.gsx:3:1
func Card(_gsxp CardProps) gsx.Node {
	return gsx.Func(func(ctx context.Context, _gsxw io.Writer) error {
		children := _gsxp.Children
		_gsxgw := gsx.W(_gsxw)
//line card.gsx:4:2
		_gsxgw.S("<section class=\"")
		_gsxgw.Class(_gsxcm.Merge, gsx.Class("px-4 py-2"), gsx.Class(_gsxp.Attrs.Class()))
		_gsxgw.S("\"")
		_gsxgw.StyleMerged("", _gsxp.Attrs.Style())
		_gsxgw.Spread(ctx, _gsxp.Attrs.Without("class", "style"))
		_gsxgw.S(">")
//line card.gsx:4:42
		_gsxgw.Node(ctx, children)
		_gsxgw.S("</section>")
		return _gsxgw.Err()
	})
}
