// Command mkstdlibindex writes internal/codegen/stdlibindex_gen.go: a
// package-name -> import-path table for the Go standard library.
//
// The table exists so the language server can resolve an undefined qualifier
// like `fmt` to an import path WITHOUT a filesystem scan. It complements the
// module's dependency graph, which covers only std packages the module already
// reaches.
//
// `go list std` is run under a pinned GOOS=linux/GOARCH=amd64/CGO_ENABLED=0
// environment (stdpath.GoListEnv) rather than the host's own, because `go
// list std` is itself host-dependent — most notably, cgo-enabled hosts
// additionally report package `cgo` at runtime/cgo. Without pinning, the
// baked table would silently differ depending on which machine ran `go
// generate`, and TestStdlibIndexIsFresh (which re-derives the table with a
// live `go list std`) would only agree with it by construction on that same
// machine. See stdpath.GoListEnv's doc comment for the full rationale and the
// resulting trade-off (GOOS-specific packages like syscall/js are not
// indexed).
//
// Regenerate with: go generate ./internal/codegen
package main

import (
	"bytes"
	"fmt"
	goformat "go/format"
	"maps"
	"os"
	"os/exec"
	"slices"
	"strings"

	"github.com/gsxhq/gsx/internal/codegen/stdpath"
)

func main() {
	cmd := exec.Command("go", "list", "-f", "{{.Name}} {{.ImportPath}}", "std")
	cmd.Env = stdpath.GoListEnv()
	out, err := cmd.Output()
	if err != nil {
		fmt.Fprintf(os.Stderr, "go list std: %v\n", err)
		os.Exit(1)
	}
	index := map[string][]string{}
	for line := range strings.SplitSeq(string(out), "\n") {
		f := strings.Fields(line)
		if len(f) != 2 {
			continue
		}
		name, path := f[0], f[1]
		if !stdpath.Importable(path) {
			continue
		}
		index[name] = append(index[name], path)
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by mkstdlibindex; DO NOT EDIT.\n\npackage codegen\n\n")
	b.WriteString("// stdlibIndex maps a standard-library package's declared NAME to the import\n")
	b.WriteString("// path(s) that declare it. A name maps to more than one path only for the few\n")
	b.WriteString("// genuine collisions (rand, template, scanner, pprof, json, asn1); those are\n")
	b.WriteString("// disambiguated by checking which candidate actually exports the wanted symbol.\n")
	b.WriteString("//\n")
	b.WriteString("// Built from `go list std` under a pinned GOOS=linux GOARCH=amd64\n")
	b.WriteString("// CGO_ENABLED=0 (stdpath.GoListEnv), not the host's own environment: `go list\n")
	b.WriteString("// std` is itself GOOS/GOARCH/cgo-dependent (e.g. package `cgo` at runtime/cgo\n")
	b.WriteString("// appears only when cgo is enabled), so pinning is what makes this table a\n")
	b.WriteString("// fixed, reproducible artifact instead of a snapshot of whichever machine ran\n")
	b.WriteString("// `go generate`. A GOOS-specific package such as syscall/js is therefore not\n")
	b.WriteString("// indexed; see stdpath.GoListEnv's doc comment.\n")
	b.WriteString("var stdlibIndex = map[string][]string{\n")
	for _, name := range slices.Sorted(maps.Keys(index)) {
		paths := index[name]
		slices.Sort(paths)
		fmt.Fprintf(&b, "\t%q: {", name)
		for i, p := range paths {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%q", p)
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")

	src, err := goformat.Source(b.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile("stdlibindex_gen.go", src, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}
}
