// Command mkstdlibindex writes internal/codegen/stdlibindex_gen.go: a
// package-name -> import-path table for the Go standard library.
//
// The table exists so the language server can resolve an undefined qualifier
// like `fmt` to an import path WITHOUT a filesystem scan. It complements the
// module's dependency graph, which covers only std packages the module already
// reaches.
//
// Regenerate with: go generate ./internal/codegen
package main

import (
	"bytes"
	"fmt"
	goformat "go/format"
	"maps"
	"os"
	"os/exec"
	"slices"
	"strings"
)

func main() {
	out, err := exec.Command("go", "list", "-f", "{{.Name}} {{.ImportPath}}", "std").Output()
	if err != nil {
		fmt.Fprintf(os.Stderr, "go list std: %v\n", err)
		os.Exit(1)
	}
	index := map[string][]string{}
	for line := range strings.SplitSeq(string(out), "\n") {
		f := strings.Fields(line)
		if len(f) != 2 {
			continue
		}
		name, path := f[0], f[1]
		// `internal/…` is unimportable; `vendor/…` is not a real std package.
		if strings.Contains(path, "internal/") || strings.HasPrefix(path, "vendor/") {
			continue
		}
		index[name] = append(index[name], path)
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by mkstdlibindex; DO NOT EDIT.\n\npackage codegen\n\n")
	b.WriteString("// stdlibIndex maps a standard-library package's declared NAME to the import\n")
	b.WriteString("// path(s) that declare it. A name maps to more than one path only for the few\n")
	b.WriteString("// genuine collisions (rand, template, scanner, pprof, json, asn1); those are\n")
	b.WriteString("// disambiguated by checking which candidate actually exports the wanted symbol.\n")
	b.WriteString("var stdlibIndex = map[string][]string{\n")
	for _, name := range slices.Sorted(maps.Keys(index)) {
		paths := index[name]
		slices.Sort(paths)
		fmt.Fprintf(&b, "\t%q: {", name)
		for i, p := range paths {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%q", p)
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")

	src, err := goformat.Source(b.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile("stdlibindex_gen.go", src, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}
}
