package corpus

import (
	"bytes"
	"go/token"
	"path/filepath"
	"strings"
	"testing"

	"github.com/gsxhq/gsx/internal/codegen"
	"github.com/gsxhq/gsx/internal/diag"
)

func TestBatchCodegenSingleAndMulti(t *testing.T) {
	if testing.Short() {
		t.Skip("skip batch build in -short")
	}
	repoRoot, err := filepath.Abs("../..")
	if err != nil {
		t.Fatalf("resolve repo root: %v", err)
	}
	single, err := loadCase("testdata/loadertest/single.txtar")
	if err != nil {
		t.Fatalf("load single: %v", err)
	}
	multi, err := loadCase("testdata/loadertest/multi.txtar")
	if err != nil {
		t.Fatalf("load multi: %v", err)
	}
	out, err := batchCodegen(repoRoot, []*caseDoc{single, multi})
	if err != nil {
		t.Fatal(err)
	}
	if d, _ := htmlStructuralDiff(out["loadertest/single"].html, "<p>Hi X</p>"); d != "" {
		t.Errorf("single: %s\ngot %q", d, out["loadertest/single"].html)
	}
	if len(out["loadertest/single"].gen) == 0 {
		t.Errorf("single: expected generated bytes recorded")
	}
	if d, _ := htmlStructuralDiff(out["loadertest/multi"].html, "<button>Go</button>"); d != "" {
		t.Errorf("multi: %s\ngot %q", d, out["loadertest/multi"].html)
	}
}

// TestBatchCodegenRendererRegistryIsolation proves a corpus case's generated
// output depends only on its own module-wide renderer registry. Running another
// case with a different registry beside it must not renumber the reserved
// renderer alias or otherwise change its generated bytes.
func TestBatchCodegenRendererRegistryIsolation(t *testing.T) {
	if testing.Short() {
		t.Skip("skip batch build in -short")
	}
	repoRoot, err := filepath.Abs("../..")
	if err != nil {
		t.Fatalf("resolve repo root: %v", err)
	}
	other, err := loadCase("testdata/cases/renderers/attr_basic.txtar")
	if err != nil {
		t.Fatalf("load other renderer case: %v", err)
	}
	target, err := loadCase("testdata/cases/renderers/text_basic.txtar")
	if err != nil {
		t.Fatalf("load target renderer case: %v", err)
	}

	alone, err := batchCodegen(repoRoot, []*caseDoc{target})
	if err != nil {
		t.Fatalf("target alone: %v", err)
	}
	beside, err := batchCodegen(repoRoot, []*caseDoc{other, target})
	if err != nil {
		t.Fatalf("target beside another registry: %v", err)
	}
	if !bytes.Equal(alone[target.name].gen, beside[target.name].gen) {
		t.Fatalf("target generated output changed beside a different renderer registry\n--- alone ---\n%s\n--- beside ---\n%s", alone[target.name].gen, beside[target.name].gen)
	}
}

func TestPartitionCodegenCandidatesByOrderedRendererRegistry(t *testing.T) {
	a := codegen.RendererAlias{TypeKey: "example.com/model.A", PkgPath: "example.com/render", FuncName: "A"}
	b := codegen.RendererAlias{TypeKey: "example.com/model.B", PkgPath: "example.com/render", FuncName: "B"}
	noRendererA := &caseDoc{name: "no-renderer-a"}
	orderedA := &caseDoc{name: "ordered-a", renderers: []codegen.RendererAlias{a, b}}
	noRendererB := &caseDoc{name: "no-renderer-b", renderers: []codegen.RendererAlias{}}
	orderedB := &caseDoc{name: "ordered-b", renderers: []codegen.RendererAlias{a, b}}
	reversed := &caseDoc{name: "reversed", renderers: []codegen.RendererAlias{b, a}}
	different := &caseDoc{name: "different", renderers: []codegen.RendererAlias{a}}

	groups := partitionCodegenCandidatesByRendererRegistry([]*caseDoc{
		noRendererA, orderedA, noRendererB, orderedB, reversed, different,
	})
	if len(groups) != 4 {
		t.Fatalf("group count = %d, want 4", len(groups))
	}
	if len(groups[0]) != 2 || groups[0][0] != noRendererA || groups[0][1] != noRendererB {
		t.Fatalf("empty-registry group = %#v, want both no-renderer cases", groups[0])
	}
	if len(groups[1]) != 2 || groups[1][0] != orderedA || groups[1][1] != orderedB {
		t.Fatalf("identical ordered-registry group = %#v, want both ordered cases", groups[1])
	}
	if len(groups[2]) != 1 || groups[2][0] != reversed {
		t.Fatalf("reversed-registry group = %#v, want reversed alone", groups[2])
	}
	if len(groups[3]) != 1 || groups[3][0] != different {
		t.Fatalf("different-registry group = %#v, want different alone", groups[3])
	}
}

// TestFormatDiagLine pins the three diagBuf line shapes formatDiagLine
// produces: a positioned error (no severity prefix, so existing
// diagnostics.golden files pinned before severity prefixes were added stay
// unchanged), a positioned warning ("warning: " prefix), and a positionless
// error (message only, no "0:0:").
func TestFormatDiagLine(t *testing.T) {
	tests := []struct {
		name string
		d    diag.Diagnostic
		want string
	}{
		{
			name: "positioned error has no severity prefix",
			d: diag.Diagnostic{
				Start:    token.Position{Line: 3, Column: 5},
				Severity: diag.Error,
				Message:  "boom",
			},
			want: "3:5: boom\n",
		},
		{
			name: "positioned warning gets a warning prefix",
			d: diag.Diagnostic{
				Start:    token.Position{Line: 6, Column: 2},
				Severity: diag.Warning,
				Message:  "needs an explicit type arg",
			},
			want: "6:2: warning: needs an explicit type arg\n",
		},
		{
			name: "positionless diagnostic has no line:col",
			d: diag.Diagnostic{
				Severity: diag.Error,
				Message:  "package-level failure",
			},
			want: "package-level failure\n",
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			var buf bytes.Buffer
			formatDiagLine(&buf, tc.d)
			if got := buf.String(); got != tc.want {
				t.Errorf("formatDiagLine: got %q, want %q", got, tc.want)
			}
		})
	}
}

// TestBatchCodegenWarningOnlyCasePopulatesDiagAndBuilds is the end-to-end
// proof for the fix in batch.go: a case whose only diagnostic is a Warning
// (not an Error) must still get a non-empty caseCodegen.diag — the field's
// doc says "empty if clean", and a warning-only case is not clean — while
// remaining buildable/renderable (cg.hasErr must stay false, gating
// buildability separately from diag's emptiness). Before the fix, cg.diag
// was only ever populated inside the `if hasErr` branch, so a warning-only
// case silently wrote an empty diagnostics.golden.
//
// xpkg/generic_inference_unavailable_warning.txtar exercises the one
// reachable warning path in codegen (infer.go's recordInferenceUnavailable,
// "inference-unavailable"): an imported generic component's type-param
// constraint references an unexported dep-local type, so the ONE offending
// tag's probe is skipped with a Warning while the sibling tag in the same
// file still generates and renders.
func TestBatchCodegenWarningOnlyCasePopulatesDiagAndBuilds(t *testing.T) {
	repoRoot, err := filepath.Abs("../..")
	if err != nil {
		t.Fatalf("resolve repo root: %v", err)
	}
	c, err := loadCase("testdata/cases/xpkg/generic_inference_unavailable_warning.txtar")
	if err != nil {
		t.Fatalf("load case: %v", err)
	}
	out, err := batchCodegen(repoRoot, []*caseDoc{c})
	if err != nil {
		t.Fatal(err)
	}
	cg := out[c.name]
	if cg == nil {
		t.Fatalf("batchCodegen returned no result for %s", c.name)
	}
	if cg.hasErr {
		t.Errorf("hasErr = true for a warning-only case; want false (an error-only gate must not treat warnings as errors)")
	}
	if len(cg.diag) == 0 {
		t.Fatalf("cg.diag is empty for a warning-only case; want the formatted warning line (empty means \"clean\", and a warning is not clean)")
	}
	if !strings.Contains(string(cg.diag), "warning: ") {
		t.Errorf("cg.diag = %q; want a \"warning: \" prefixed line", cg.diag)
	}
	if !strings.Contains(string(cg.diag), "components.Widget") {
		t.Errorf("cg.diag = %q; want it to name the offending tag <components.Widget>", cg.diag)
	}
	if len(cg.gen) == 0 {
		t.Errorf("cg.gen is empty; a warning-only case must still generate the unaffected sibling tag")
	}
	if d, _ := htmlStructuralDiff(cg.html, "<button>ok</button>"); d != "" {
		t.Errorf("render: %s\ngot %q", d, cg.html)
	}
}
